In [1]:
import my_methods as mm
import pandas as pd
import numpy as np
import datetime as dt
from sklearn.linear_model import LinearRegression
"""
股票周度回报率关于市值加权市场回报率的beta
股票周度回报率，市值加权市场周度回报率
取样时长为当月的前三年，且至少有52周数据
"""

'\n股票周度回报率关于市值加权市场回报率的beta\n股票周度回报率，市值加权市场周度回报率\n取样时长为当月的前三年，且至少有52周数据\n'

# beta

In [2]:
df1 = pd.read_csv('../../Data/raw_data/12周个股回报率/TRD_Week.csv')
df2 = pd.read_csv('../../Data/raw_data/12周个股回报率/TRD_Week1.csv')
df3 = pd.read_csv('../../Data/raw_data/12周个股回报率/TRD_Week2.csv')
df = pd.concat([df1,df2,df3])
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Trdwnt'] = pd.to_datetime([x+'-5' for x in df['Trdwnt']], format='%Y-%W-%w') - pd.DateOffset(weeks=1)
df

,Stkcd,Trdwnt,Opndt,Wopnprc,Clsdt,Wclsprc,Wnshrtrd,Wnvaltrd,Wsmvosd,Wsmvttl,Ndaytrd,Wretwd,Wretnd,Markettype,Capchgdt,Ahshrtrd_W,Ahvaltrd_W
0,1,1991-04-05,1991-04-03,49.00,1991-04-06,48.28,1300,64000.0,1279420.00,2341588.26,4,NaN,NaN,4,1991-04-03,NaN,NaN
1,1,1991-04-12,1991-04-08,48.04,1991-04-13,46.84,3400,161000.0,1241260.00,2271748.01,5,-0.029826,-0.029826,4,1991-04-03,NaN,NaN
2,1,1991-04-19,1991-04-16,46.38,1991-04-20,45.46,1400,64000.0,1204690.00,2204817.77,5,-0.029462,-0.029462,4,1991-04-03,NaN,NaN
3,1,1991-04-26,1991-04-23,45.00,1991-04-26,44.34,6700,300000.0,1175010.00,2150497.58,4,-0.024637,-0.024637,4,1991-04-03,NaN,NaN
4,1,1991-05-03,1991-04-29,43.90,1991-05-04,43.02,1300,57000.0,1140030.00,2086477.36,5,-0.029770,0.365088,4,1991-04-03,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655361,605599,2022-01-14,2022-01-10,13.71,2022-01-14,13.89,61071792,868917660.0,1080333.64,10803333.64,5,-0.000719,-0.000719,1,2021-09-09,0.0,0.0
655362,605599,2022-01-21,2022-01-17,13.76,2022-01-21,13.15,30112749,404360677.0,1022778.07,10227778.07,5,-0.053276,-0.053276,1,2021-09-09,0.0,0.0
655363,605599,2022-01-28,2022-01-24,13.19,2022-01-28,11.89,23896420,300780958.0,924778.04,9247778.04,5,-0.095817,-0.095817,1,2021-09-09,0.0,0.0
655364,605599,2022-02-11,2022-02-07,13.08,2022-02-11,12.63,64437261,859338170.0,982333.61,9823333.61,5,0.062237,0.062237,1,2021-09-09,0.0,0.0
655365,605599,2022-02-18,2022-02-14,12.88,2022-02-18,12.41,33646695,426113969.0,965222.50,9652222.50,5,-0.017419,-0.017419,1,2021-09-09,0.0,0.0

In [3]:
wret = df.pivot_table(values='Wretwd', index='Trdwnt', columns='Stkcd')
wret

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdwnt,,,,,,,,,,,,,,,,,,,,,
1990-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-11,NaN,NaN,NaN,NaN,-0.032169,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-18,NaN,NaN,NaN,NaN,-0.023496,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-14,-0.050581,-0.054363,NaN,0.027936,-0.004329,-0.022026,-0.032544,-0.034965,0.036638,0.000000,...,-0.007722,0.013539,-0.012342,0.190526,0.039273,-0.008997,-0.005851,-0.009187,-0.133755,-0.000719
2022-01-21,0.062462,0.045411,NaN,-0.027176,-0.082609,0.015766,0.045872,-0.043478,-0.024948,-0.041667,...,-0.020752,-0.036145,-0.050321,-0.170092,-0.102869,-0.056420,-0.037871,0.000281,-0.108366,-0.053276
2022-01-28,-0.087608,-0.060536,NaN,-0.011837,0.014218,-0.048780,-0.068713,-0.034091,-0.089552,-0.086957,...,0.065563,-0.039946,-0.039829,-0.154373,-0.039002,-0.057732,-0.058245,-0.098034,-0.074937,-0.095817
2022-02-11,0.080227,0.041810,NaN,0.145664,0.037383,0.062937,-0.001570,0.000000,0.025761,0.062500,...,-0.027346,-0.057458,0.029630,-0.003738,0.138799,0.025529,0.017227,0.010900,0.157931,0.062237
2022-02-18,-0.019298,-0.033050,NaN,-0.079046,0.009009,-0.006579,0.042453,0.129412,0.062405,0.075630,...,-0.093610,0.034535,0.001439,-0.016260,-0.027085,0.009246,0.018323,0.023721,0.019988,-0.017419

In [4]:
df = pd.read_csv('../../Data/raw_data/13周市场回报率/TRD_Weekcm.csv', index_col='Trdwnt')
df

,Markettype,Cwretwdeq,Cwretmdeq,Cwretwdos,Cwretmdos,Cwretwdtl,Cwretmdtl,Cwnstkcal,Cwmvosd,Cwmvttl
Trdwnt,,,,,,,,,,
1990-51,5,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-51,15,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-51,21,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-51,31,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-51,37,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
...,...,...,...,...,...,...,...,...,...,...
2022-08,95,0.021412,0.021412,0.012942,0.012942,0.013176,0.013176,4417,6.952267e+10,8.180199e+10
2022-08,101,0.019014,0.019014,0.010552,0.010552,0.011044,0.011044,3613,6.268145e+10,7.418671e+10
2022-08,111,0.018615,0.018615,0.010533,0.010533,0.011023,0.011023,3703,6.280993e+10,7.433842e+10
2022-08,117,0.022228,0.022228,0.013492,0.013492,0.014248,0.014248,4718,7.133980e+10,8.659607e+10
2022-08,127,0.021861,0.021861,0.013470,0.013470,0.014224,0.014224,4808,7.146828e+10,8.674778e+10

In [5]:
# YY-WW格式转换为日期必须明确是周内的第几天，0为周日(最后一天)，5为周五
# 日期format: %W指当年第几周，%w指当周第几天
# [x... for x in y if x...]可快速转换序列
# 但CSMAR原始数据与pandas.to_datetime对当年第几周的理解似乎有些差异(观察最后一天2022/2/18)
# 故再减去7天的DatetimeDelta
df.index = pd.to_datetime([x+'-5' for x in df.index], format='%Y-%W-%w') - pd.DateOffset(days=7)
df

,Markettype,Cwretwdeq,Cwretmdeq,Cwretwdos,Cwretmdos,Cwretwdtl,Cwretmdtl,Cwnstkcal,Cwmvosd,Cwmvttl
1990-12-14,5,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-12-14,15,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-12-14,21,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-12-14,31,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
1990-12-14,37,NaN,NaN,NaN,NaN,NaN,NaN,6,5.373582e+05,1.813406e+06
...,...,...,...,...,...,...,...,...,...,...
2022-02-18,95,0.021412,0.021412,0.012942,0.012942,0.013176,0.013176,4417,6.952267e+10,8.180199e+10
2022-02-18,101,0.019014,0.019014,0.010552,0.010552,0.011044,0.011044,3613,6.268145e+10,7.418671e+10
2022-02-18,111,0.018615,0.018615,0.010533,0.010533,0.011023,0.011023,3703,6.280993e+10,7.433842e+10
2022-02-18,117,0.022228,0.022228,0.013492,0.013492,0.014248,0.014248,4718,7.133980e+10,8.659607e+10
2022-02-18,127,0.021861,0.021861,0.013470,0.013470,0.014224,0.014224,4808,7.146828e+10,8.674778e+10

In [6]:
market_wret = df[df['Markettype'] == 5].loc[:,'Cwretwdtl']  # 5=沪深A股市场（不包含科创板、创业板）
# Cwretwdtl [考虑现金红利再投资的综合周市场回报率(总市值加权平均法)]
market_wret

1990-12-14         NaN
1990-12-21    0.141059
1990-12-28    0.010085
1991-01-04    0.030370
1991-01-11   -0.001556
                ...
2022-01-14   -0.017332
2022-01-21   -0.002458
2022-01-28   -0.047686
2022-02-11    0.029990
2022-02-18    0.009622
Name: Cwretwdtl, Length: 1590, dtype: float64

In [7]:
wbeta = pd.DataFrame(columns=wret.columns, index=wret.index)
model = LinearRegression()
for endday in wret.index:
    print(endday)
    beginday = endday - pd.DateOffset(years=3)
    for stock in wret.columns:
        y = wret.loc[beginday:endday,stock]
        x = market_wret[beginday:endday]
        s = pd.concat([y,x], axis=1)
        s = s.dropna()
        if len(s) <52:
            continue
        y = s.iloc[:,0].to_numpy()
        X = s.iloc[:,[1]].to_numpy()
        model.fit(y=y, X=X)
        wbeta.loc[endday, stock] = model.coef_[0]

1990-12-21 00:00:00
1990-12-28 00:00:00
1991-01-04 00:00:00
1991-01-11 00:00:00
1991-01-18 00:00:00
1991-01-25 00:00:00
1991-02-01 00:00:00
1991-02-08 00:00:00
1991-02-15 00:00:00
1991-02-22 00:00:00
1991-03-01 00:00:00
1991-03-08 00:00:00
1991-03-15 00:00:00
1991-03-22 00:00:00
1991-03-29 00:00:00
1991-04-05 00:00:00
1991-04-12 00:00:00
1991-04-19 00:00:00
1991-04-26 00:00:00
1991-05-03 00:00:00
1991-05-10 00:00:00
1991-05-17 00:00:00
1991-05-24 00:00:00
1991-05-31 00:00:00
1991-06-07 00:00:00
1991-06-14 00:00:00
1991-06-21 00:00:00
1991-06-28 00:00:00
1991-07-05 00:00:00
1991-07-12 00:00:00
1991-07-19 00:00:00
1991-07-26 00:00:00
1991-08-02 00:00:00
1991-08-09 00:00:00
1991-08-16 00:00:00
1991-08-23 00:00:00
1991-08-30 00:00:00
1991-09-06 00:00:00
1991-09-13 00:00:00
1991-09-20 00:00:00
1991-09-27 00:00:00
1991-10-04 00:00:00
1991-10-11 00:00:00
1991-10-18 00:00:00
1991-10-25 00:00:00
1991-11-01 00:00:00
1991-11-08 00:00:00
1991-11-15 00:00:00
1991-11-22 00:00:00
1991-11-29 00:00:00
1991-12-06 00:00:00
1991-12-13 00:00:00
1991-12-20 00:00:00
1991-12-27 00:00:00
1992-01-03 00:00:00
1992-01-10 00:00:00
1992-01-17 00:00:00
1992-01-24 00:00:00
1992-01-31 00:00:00
1992-02-07 00:00:00
1992-02-14 00:00:00
1992-02-21 00:00:00
1992-02-28 00:00:00
1992-03-06 00:00:00
1992-03-13 00:00:00
1992-03-20 00:00:00
1992-03-27 00:00:00
1992-04-03 00:00:00
1992-04-10 00:00:00
1992-04-17 00:00:00
1992-04-24 00:00:00
1992-05-01 00:00:00
1992-05-08 00:00:00
1992-05-15 00:00:00
1992-05-22 00:00:00
1992-05-29 00:00:00
1992-06-05 00:00:00
1992-06-12 00:00:00
1992-06-19 00:00:00
1992-06-26 00:00:00
1992-07-03 00:00:00
1992-07-10 00:00:00
1992-07-17 00:00:00
1992-07-24 00:00:00
1992-07-31 00:00:00
1992-08-07 00:00:00
1992-08-14 00:00:00
1992-08-21 00:00:00
1992-08-28 00:00:00
1992-09-04 00:00:00
1992-09-11 00:00:00
1992-09-18 00:00:00
1992-09-25 00:00:00
1992-10-02 00:00:00
1992-10-09 00:00:00
1992-10-16 00:00:00
1992-10-23 00:00:00
1992-10-30 00:00:00
1992-11-06 00:00:00
1992-11-13 00:00:00
1992-11-20 00:00:00
1992-11-27 00:00:00
1992-12-04 00:00:00
1992-12-11 00:00:00
1992-12-18 00:00:00
1992-12-25 00:00:00
1993-01-01 00:00:00
1993-01-08 00:00:00
1993-01-15 00:00:00
1993-01-22 00:00:00
1993-01-29 00:00:00
1993-02-05 00:00:00
1993-02-12 00:00:00
1993-02-19 00:00:00
1993-02-26 00:00:00
1993-03-05 00:00:00
1993-03-12 00:00:00
1993-03-19 00:00:00
1993-03-26 00:00:00
1993-04-02 00:00:00
1993-04-09 00:00:00
1993-04-16 00:00:00
1993-04-23 00:00:00
1993-04-30 00:00:00
1993-05-07 00:00:00
1993-05-14 00:00:00
1993-05-21 00:00:00
1993-05-28 00:00:00
1993-06-04 00:00:00
1993-06-11 00:00:00
1993-06-18 00:00:00
1993-06-25 00:00:00
1993-07-02 00:00:00
1993-07-09 00:00:00
1993-07-16 00:00:00
1993-07-23 00:00:00
1993-07-30 00:00:00
1993-08-06 00:00:00
1993-08-13 00:00:00
1993-08-20 00:00:00
1993-08-27 00:00:00
1993-09-03 00:00:00
1993-09-10 00:00:00
1993-09-17 00:00:00
1993-09-24 00:00:00
1993-10-01 00:00:00
1993-10-08 00:00:00
1993-10-15 00:00:00
1993-10-22 00:00:00
1993-10-29 00:00:00
1993-11-05 00:00:00
1993-11-12 00:00:00
1993-11-19 00:00:00
1993-11-26 00:00:00
1993-12-03 00:00:00
1993-12-10 00:00:00
1993-12-17 00:00:00
1993-12-24 00:00:00
1993-12-31 00:00:00
1994-01-07 00:00:00
1994-01-14 00:00:00
1994-01-21 00:00:00
1994-01-28 00:00:00
1994-02-04 00:00:00
1994-02-18 00:00:00
1994-02-25 00:00:00
1994-03-04 00:00:00
1994-03-11 00:00:00
1994-03-18 00:00:00
1994-03-25 00:00:00
1994-04-01 00:00:00
1994-04-08 00:00:00
1994-04-15 00:00:00
1994-04-22 00:00:00
1994-04-29 00:00:00
1994-05-06 00:00:00
1994-05-13 00:00:00
1994-05-20 00:00:00
1994-05-27 00:00:00
1994-06-03 00:00:00
1994-06-10 00:00:00
1994-06-17 00:00:00
1994-06-24 00:00:00
1994-07-01 00:00:00
1994-07-08 00:00:00
1994-07-15 00:00:00
1994-07-22 00:00:00
1994-07-29 00:00:00
1994-08-05 00:00:00
1994-08-12 00:00:00
1994-08-19 00:00:00
1994-08-26 00:00:00
1994-09-02 00:00:00
1994-09-09 00:00:00
1994-09-16 00:00:00
1994-09-23 00:00:00
1994-09-30 00:00:00
1994-10-07 00:00:00
1994-10-14 00:00:00
1994-10-21 00:00:00
1994-10-28 00:00:00
1994-11-04 00:00:00
1994-11-11 00:00:00
1994-11-18 00:00:00
1994-11-25 00:00:00
1994-12-02 00:00:00
1994-12-09 00:00:00
1994-12-16 00:00:00
1994-12-23 00:00:00
1994-12-30 00:00:00
1995-01-06 00:00:00
1995-01-13 00:00:00
1995-01-20 00:00:00
1995-02-03 00:00:00
1995-02-10 00:00:00
1995-02-17 00:00:00
1995-02-24 00:00:00
1995-03-03 00:00:00
1995-03-10 00:00:00
1995-03-17 00:00:00
1995-03-24 00:00:00
1995-03-31 00:00:00
1995-04-07 00:00:00
1995-04-14 00:00:00
1995-04-21 00:00:00
1995-04-28 00:00:00
1995-05-05 00:00:00
1995-05-12 00:00:00
1995-05-19 00:00:00
1995-05-26 00:00:00
1995-06-02 00:00:00
1995-06-09 00:00:00
1995-06-16 00:00:00
1995-06-23 00:00:00
1995-06-30 00:00:00
1995-07-07 00:00:00
1995-07-14 00:00:00
1995-07-21 00:00:00
1995-07-28 00:00:00
1995-08-04 00:00:00
1995-08-11 00:00:00
1995-08-18 00:00:00
1995-08-25 00:00:00
1995-09-01 00:00:00
1995-09-08 00:00:00
1995-09-15 00:00:00
1995-09-22 00:00:00
1995-09-29 00:00:00
1995-10-06 00:00:00
1995-10-13 00:00:00
1995-10-20 00:00:00
1995-10-27 00:00:00
1995-11-03 00:00:00
1995-11-10 00:00:00
1995-11-17 00:00:00
1995-11-24 00:00:00
1995-12-01 00:00:00
1995-12-08 00:00:00
1995-12-15 00:00:00
1995-12-22 00:00:00
1995-12-29 00:00:00
1996-01-05 00:00:00
1996-01-12 00:00:00
1996-01-19 00:00:00
1996-01-26 00:00:00
1996-02-02 00:00:00
1996-02-09 00:00:00
1996-03-01 00:00:00
1996-03-08 00:00:00
1996-03-15 00:00:00
1996-03-22 00:00:00
1996-03-29 00:00:00
1996-04-05 00:00:00
1996-04-12 00:00:00
1996-04-19 00:00:00
1996-04-26 00:00:00
1996-05-03 00:00:00
1996-05-10 00:00:00
1996-05-17 00:00:00
1996-05-24 00:00:00
1996-05-31 00:00:00
1996-06-07 00:00:00
1996-06-14 00:00:00
1996-06-21 00:00:00
1996-06-28 00:00:00
1996-07-05 00:00:00
1996-07-12 00:00:00
1996-07-19 00:00:00
1996-07-26 00:00:00
1996-08-02 00:00:00
1996-08-09 00:00:00
1996-08-16 00:00:00
1996-08-23 00:00:00
1996-08-30 00:00:00
1996-09-06 00:00:00
1996-09-13 00:00:00
1996-09-20 00:00:00
1996-09-27 00:00:00
1996-10-04 00:00:00
1996-10-11 00:00:00
1996-10-18 00:00:00
1996-10-25 00:00:00
1996-11-01 00:00:00
1996-11-08 00:00:00
1996-11-15 00:00:00
1996-11-22 00:00:00
1996-11-29 00:00:00
1996-12-06 00:00:00
1996-12-13 00:00:00
1996-12-20 00:00:00
1996-12-27 00:00:00
1997-01-03 00:00:00
1997-01-10 00:00:00
1997-01-17 00:00:00
1997-01-24 00:00:00
1997-01-31 00:00:00
1997-02-21 00:00:00
1997-02-28 00:00:00
1997-03-07 00:00:00
1997-03-14 00:00:00
1997-03-21 00:00:00
1997-03-28 00:00:00
1997-04-04 00:00:00
1997-04-11 00:00:00
1997-04-18 00:00:00
1997-04-25 00:00:00
1997-05-02 00:00:00
1997-05-09 00:00:00
1997-05-16 00:00:00
1997-05-23 00:00:00
1997-05-30 00:00:00
1997-06-06 00:00:00
1997-06-13 00:00:00
1997-06-20 00:00:00
1997-06-27 00:00:00
1997-07-04 00:00:00
1997-07-11 00:00:00
1997-07-18 00:00:00
1997-07-25 00:00:00
1997-08-01 00:00:00
1997-08-08 00:00:00
1997-08-15 00:00:00
1997-08-22 00:00:00
1997-08-29 00:00:00
1997-09-05 00:00:00
1997-09-12 00:00:00
1997-09-19 00:00:00
1997-09-26 00:00:00
1997-10-03 00:00:00
1997-10-10 00:00:00
1997-10-17 00:00:00
1997-10-24 00:00:00
1997-10-31 00:00:00
1997-11-07 00:00:00
1997-11-14 00:00:00
1997-11-21 00:00:00
1997-11-28 00:00:00
1997-12-05 00:00:00
1997-12-12 00:00:00
1997-12-19 00:00:00
1997-12-26 00:00:00
1998-01-02 00:00:00
1998-01-09 00:00:00
1998-01-16 00:00:00
1998-01-23 00:00:00
1998-02-13 00:00:00
1998-02-20 00:00:00
1998-02-27 00:00:00
1998-03-06 00:00:00
1998-03-13 00:00:00
1998-03-20 00:00:00
1998-03-27 00:00:00
1998-04-03 00:00:00
1998-04-10 00:00:00
1998-04-17 00:00:00
1998-04-24 00:00:00
1998-05-01 00:00:00
1998-05-08 00:00:00
1998-05-15 00:00:00
1998-05-22 00:00:00
1998-05-29 00:00:00
1998-06-05 00:00:00
1998-06-12 00:00:00
1998-06-19 00:00:00
1998-06-26 00:00:00
1998-07-03 00:00:00
1998-07-10 00:00:00
1998-07-17 00:00:00
1998-07-24 00:00:00
1998-07-31 00:00:00
1998-08-07 00:00:00
1998-08-14 00:00:00
1998-08-21 00:00:00
1998-08-28 00:00:00
1998-09-04 00:00:00
1998-09-11 00:00:00
1998-09-18 00:00:00
1998-09-25 00:00:00
1998-10-02 00:00:00
1998-10-09 00:00:00
1998-10-16 00:00:00
1998-10-23 00:00:00
1998-10-30 00:00:00
1998-11-06 00:00:00
1998-11-13 00:00:00
1998-11-20 00:00:00
1998-11-27 00:00:00
1998-12-04 00:00:00
1998-12-11 00:00:00
1998-12-18 00:00:00

1998-12-25 00:00:00
1999-01-01 00:00:00
1999-01-08 00:00:00
1999-01-15 00:00:00
1999-01-22 00:00:00
1999-01-29 00:00:00
1999-02-05 00:00:00
1999-02-12 00:00:00
1999-03-05 00:00:00
1999-03-12 00:00:00
1999-03-19 00:00:00
1999-03-26 00:00:00
1999-04-02 00:00:00
1999-04-09 00:00:00
1999-04-16 00:00:00
1999-04-23 00:00:00
1999-04-30 00:00:00
1999-05-07 00:00:00
1999-05-14 00:00:00
1999-05-21 00:00:00
1999-05-28 00:00:00
1999-06-04 00:00:00
1999-06-11 00:00:00
1999-06-18 00:00:00
1999-06-25 00:00:00
1999-07-02 00:00:00
1999-07-09 00:00:00
1999-07-16 00:00:00
1999-07-23 00:00:00
1999-07-30 00:00:00
1999-08-06 00:00:00
1999-08-13 00:00:00
1999-08-20 00:00:00
1999-08-27 00:00:00
1999-09-03 00:00:00
1999-09-10 00:00:00
1999-09-17 00:00:00
1999-09-24 00:00:00
1999-10-01 00:00:00
1999-10-08 00:00:00
1999-10-15 00:00:00
1999-10-22 00:00:00
1999-10-29 00:00:00
1999-11-05 00:00:00
1999-11-12 00:00:00
1999-11-19 00:00:00
1999-11-26 00:00:00
1999-12-03 00:00:00
1999-12-10 00:00:00
1999-12-17 00:00:00
1999-12-24 00:00:00
1999-12-31 00:00:00
2000-01-07 00:00:00
2000-01-14 00:00:00
2000-01-21 00:00:00
2000-01-28 00:00:00
2000-02-18 00:00:00
2000-02-25 00:00:00
2000-03-03 00:00:00
2000-03-10 00:00:00
2000-03-17 00:00:00
2000-03-24 00:00:00
2000-03-31 00:00:00
2000-04-07 00:00:00
2000-04-14 00:00:00
2000-04-21 00:00:00
2000-04-28 00:00:00
2000-05-12 00:00:00
2000-05-19 00:00:00
2000-05-26 00:00:00
2000-06-02 00:00:00
2000-06-09 00:00:00
2000-06-16 00:00:00
2000-06-23 00:00:00
2000-06-30 00:00:00
2000-07-07 00:00:00
2000-07-14 00:00:00
2000-07-21 00:00:00
2000-07-28 00:00:00
2000-08-04 00:00:00
2000-08-11 00:00:00
2000-08-18 00:00:00
2000-08-25 00:00:00
2000-09-01 00:00:00
2000-09-08 00:00:00
2000-09-15 00:00:00
2000-09-22 00:00:00
2000-09-29 00:00:00
2000-10-13 00:00:00
2000-10-20 00:00:00
2000-10-27 00:00:00
2000-11-03 00:00:00
2000-11-10 00:00:00
2000-11-17 00:00:00
2000-11-24 00:00:00
2000-12-01 00:00:00
2000-12-08 00:00:00
2000-12-15 00:00:00
2000-12-22 00:00:00
2000-12-29 00:00:00
2001-01-05 00:00:00
2001-01-12 00:00:00
2001-02-02 00:00:00
2001-02-09 00:00:00
2001-02-16 00:00:00
2001-02-23 00:00:00
2001-03-02 00:00:00
2001-03-09 00:00:00
2001-03-16 00:00:00
2001-03-23 00:00:00
2001-03-30 00:00:00
2001-04-06 00:00:00
2001-04-13 00:00:00
2001-04-20 00:00:00
2001-04-27 00:00:00
2001-05-04 00:00:00
2001-05-11 00:00:00
2001-05-18 00:00:00
2001-05-25 00:00:00
2001-06-01 00:00:00
2001-06-08 00:00:00
2001-06-15 00:00:00
2001-06-22 00:00:00
2001-06-29 00:00:00
2001-07-06 00:00:00
2001-07-13 00:00:00
2001-07-20 00:00:00
2001-07-27 00:00:00
2001-08-03 00:00:00
2001-08-10 00:00:00
2001-08-17 00:00:00
2001-08-24 00:00:00
2001-08-31 00:00:00
2001-09-07 00:00:00
2001-09-14 00:00:00
2001-09-21 00:00:00
2001-10-05 00:00:00
2001-10-12 00:00:00
2001-10-19 00:00:00
2001-10-26 00:00:00
2001-11-02 00:00:00
2001-11-09 00:00:00
2001-11-16 00:00:00
2001-11-23 00:00:00
2001-11-30 00:00:00
2001-12-07 00:00:00
2001-12-14 00:00:00
2001-12-21 00:00:00
2001-12-28 00:00:00
2002-01-04 00:00:00
2002-01-11 00:00:00
2002-01-18 00:00:00
2002-01-25 00:00:00
2002-02-01 00:00:00
2002-02-08 00:00:00
2002-03-01 00:00:00
2002-03-08 00:00:00
2002-03-15 00:00:00
2002-03-22 00:00:00
2002-03-29 00:00:00
2002-04-05 00:00:00
2002-04-12 00:00:00
2002-04-19 00:00:00
2002-04-26 00:00:00
2002-05-03 00:00:00
2002-05-10 00:00:00
2002-05-17 00:00:00
2002-05-24 00:00:00
2002-05-31 00:00:00
2002-06-07 00:00:00
2002-06-14 00:00:00
2002-06-21 00:00:00
2002-06-28 00:00:00
2002-07-05 00:00:00
2002-07-12 00:00:00
2002-07-19 00:00:00
2002-07-26 00:00:00
2002-08-02 00:00:00
2002-08-09 00:00:00
2002-08-16 00:00:00
2002-08-23 00:00:00
2002-08-30 00:00:00
2002-09-06 00:00:00
2002-09-13 00:00:00
2002-09-20 00:00:00
2002-09-27 00:00:00
2002-10-11 00:00:00
2002-10-18 00:00:00
2002-10-25 00:00:00
2002-11-01 00:00:00
2002-11-08 00:00:00
2002-11-15 00:00:00
2002-11-22 00:00:00
2002-11-29 00:00:00
2002-12-06 00:00:00
2002-12-13 00:00:00
2002-12-20 00:00:00
2002-12-27 00:00:00
2003-01-03 00:00:00
2003-01-10 00:00:00
2003-01-17 00:00:00
2003-01-24 00:00:00
2003-01-31 00:00:00
2003-02-14 00:00:00
2003-02-21 00:00:00
2003-02-28 00:00:00
2003-03-07 00:00:00
2003-03-14 00:00:00
2003-03-21 00:00:00
2003-03-28 00:00:00
2003-04-04 00:00:00
2003-04-11 00:00:00
2003-04-18 00:00:00
2003-04-25 00:00:00
2003-05-02 00:00:00
2003-05-16 00:00:00
2003-05-23 00:00:00
2003-05-30 00:00:00
2003-06-06 00:00:00
2003-06-13 00:00:00
2003-06-20 00:00:00
2003-06-27 00:00:00
2003-07-04 00:00:00
2003-07-11 00:00:00
2003-07-18 00:00:00
2003-07-25 00:00:00
2003-08-01 00:00:00
2003-08-08 00:00:00
2003-08-15 00:00:00
2003-08-22 00:00:00
2003-08-29 00:00:00
2003-09-05 00:00:00
2003-09-12 00:00:00
2003-09-19 00:00:00
2003-09-26 00:00:00
2003-10-03 00:00:00
2003-10-10 00:00:00
2003-10-17 00:00:00
2003-10-24 00:00:00
2003-10-31 00:00:00
2003-11-07 00:00:00
2003-11-14 00:00:00
2003-11-21 00:00:00
2003-11-28 00:00:00
2003-12-05 00:00:00
2003-12-12 00:00:00
2003-12-19 00:00:00
2003-12-26 00:00:00
2004-01-02 00:00:00
2004-01-09 00:00:00
2004-01-16 00:00:00
2004-01-30 00:00:00
2004-02-06 00:00:00
2004-02-13 00:00:00
2004-02-20 00:00:00
2004-02-27 00:00:00
2004-03-05 00:00:00
2004-03-12 00:00:00
2004-03-19 00:00:00
2004-03-26 00:00:00
2004-04-02 00:00:00
2004-04-09 00:00:00
2004-04-16 00:00:00
2004-04-23 00:00:00
2004-04-30 00:00:00
2004-05-14 00:00:00
2004-05-21 00:00:00
2004-05-28 00:00:00
2004-06-04 00:00:00
2004-06-11 00:00:00
2004-06-18 00:00:00
2004-06-25 00:00:00
2004-07-02 00:00:00
2004-07-09 00:00:00
2004-07-16 00:00:00
2004-07-23 00:00:00
2004-07-30 00:00:00
2004-08-06 00:00:00
2004-08-13 00:00:00
2004-08-20 00:00:00
2004-08-27 00:00:00
2004-09-03 00:00:00
2004-09-10 00:00:00
2004-09-17 00:00:00
2004-09-24 00:00:00
2004-10-01 00:00:00
2004-10-08 00:00:00
2004-10-15 00:00:00
2004-10-22 00:00:00
2004-10-29 00:00:00
2004-11-05 00:00:00
2004-11-12 00:00:00
2004-11-19 00:00:00
2004-11-26 00:00:00
2004-12-03 00:00:00
2004-12-10 00:00:00
2004-12-17 00:00:00
2004-12-24 00:00:00
2004-12-31 00:00:00
2005-01-07 00:00:00
2005-01-14 00:00:00
2005-01-21 00:00:00
2005-01-28 00:00:00
2005-02-04 00:00:00
2005-02-18 00:00:00
2005-02-25 00:00:00
2005-03-04 00:00:00
2005-03-11 00:00:00
2005-03-18 00:00:00
2005-03-25 00:00:00
2005-04-01 00:00:00
2005-04-08 00:00:00
2005-04-15 00:00:00
2005-04-22 00:00:00
2005-04-29 00:00:00
2005-05-13 00:00:00
2005-05-20 00:00:00
2005-05-27 00:00:00
2005-06-03 00:00:00
2005-06-10 00:00:00
2005-06-17 00:00:00
2005-06-24 00:00:00
2005-07-01 00:00:00
2005-07-08 00:00:00
2005-07-15 00:00:00
2005-07-22 00:00:00
2005-07-29 00:00:00
2005-08-05 00:00:00
2005-08-12 00:00:00
2005-08-19 00:00:00
2005-08-26 00:00:00
2005-09-02 00:00:00
2005-09-09 00:00:00
2005-09-16 00:00:00
2005-09-23 00:00:00
2005-09-30 00:00:00
2005-10-14 00:00:00
2005-10-21 00:00:00
2005-10-28 00:00:00
2005-11-04 00:00:00
2005-11-11 00:00:00
2005-11-18 00:00:00
2005-11-25 00:00:00
2005-12-02 00:00:00
2005-12-09 00:00:00
2005-12-16 00:00:00
2005-12-23 00:00:00
2005-12-30 00:00:00
2006-01-06 00:00:00
2006-01-13 00:00:00
2006-01-20 00:00:00
2006-02-03 00:00:00
2006-02-10 00:00:00
2006-02-17 00:00:00
2006-02-24 00:00:00
2006-03-03 00:00:00
2006-03-10 00:00:00
2006-03-17 00:00:00
2006-03-24 00:00:00
2006-03-31 00:00:00
2006-04-07 00:00:00
2006-04-14 00:00:00
2006-04-21 00:00:00
2006-05-05 00:00:00
2006-05-12 00:00:00
2006-05-19 00:00:00
2006-05-26 00:00:00
2006-06-02 00:00:00
2006-06-09 00:00:00
2006-06-16 00:00:00
2006-06-23 00:00:00
2006-06-30 00:00:00
2006-07-07 00:00:00
2006-07-14 00:00:00
2006-07-21 00:00:00
2006-07-28 00:00:00
2006-08-04 00:00:00
2006-08-11 00:00:00
2006-08-18 00:00:00
2006-08-25 00:00:00
2006-09-01 00:00:00
2006-09-08 00:00:00
2006-09-15 00:00:00
2006-09-22 00:00:00
2006-10-06 00:00:00
2006-10-13 00:00:00
2006-10-20 00:00:00
2006-10-27 00:00:00
2006-11-03 00:00:00
2006-11-10 00:00:00
2006-11-17 00:00:00
2006-11-24 00:00:00
2006-12-01 00:00:00
2006-12-08 00:00:00
2006-12-15 00:00:00
2006-12-22 00:00:00
2006-12-29 00:00:00
2007-01-05 00:00:00
2007-01-12 00:00:00
2007-01-19 00:00:00
2007-01-26 00:00:00
2007-02-02 00:00:00
2007-02-09 00:00:00
2007-02-23 00:00:00
2007-03-02 00:00:00
2007-03-09 00:00:00
2007-03-16 00:00:00
2007-03-23 00:00:00
2007-03-30 00:00:00
2007-04-06 00:00:00

2007-04-13 00:00:00
2007-04-20 00:00:00
2007-04-27 00:00:00
2007-05-04 00:00:00
2007-05-11 00:00:00
2007-05-18 00:00:00
2007-05-25 00:00:00
2007-06-01 00:00:00
2007-06-08 00:00:00
2007-06-15 00:00:00
2007-06-22 00:00:00
2007-06-29 00:00:00
2007-07-06 00:00:00
2007-07-13 00:00:00
2007-07-20 00:00:00
2007-07-27 00:00:00
2007-08-03 00:00:00
2007-08-10 00:00:00
2007-08-17 00:00:00
2007-08-24 00:00:00
2007-08-31 00:00:00
2007-09-07 00:00:00
2007-09-14 00:00:00
2007-09-21 00:00:00
2007-10-05 00:00:00
2007-10-12 00:00:00
2007-10-19 00:00:00
2007-10-26 00:00:00
2007-11-02 00:00:00
2007-11-09 00:00:00
2007-11-16 00:00:00
2007-11-23 00:00:00
2007-11-30 00:00:00
2007-12-07 00:00:00
2007-12-14 00:00:00
2007-12-21 00:00:00
2008-01-04 00:00:00
2008-01-11 00:00:00
2008-01-18 00:00:00
2008-01-25 00:00:00
2008-02-01 00:00:00
2008-02-08 00:00:00
2008-02-15 00:00:00
2008-02-22 00:00:00
2008-02-29 00:00:00
2008-03-07 00:00:00
2008-03-14 00:00:00
2008-03-21 00:00:00
2008-03-28 00:00:00
2008-04-04 00:00:00
2008-04-11 00:00:00
2008-04-18 00:00:00
2008-04-25 00:00:00
2008-05-02 00:00:00
2008-05-09 00:00:00
2008-05-16 00:00:00
2008-05-23 00:00:00
2008-05-30 00:00:00
2008-06-06 00:00:00
2008-06-13 00:00:00
2008-06-20 00:00:00
2008-06-27 00:00:00
2008-07-04 00:00:00
2008-07-11 00:00:00
2008-07-18 00:00:00
2008-07-25 00:00:00
2008-08-01 00:00:00
2008-08-08 00:00:00
2008-08-15 00:00:00
2008-08-22 00:00:00
2008-08-29 00:00:00
2008-09-05 00:00:00
2008-09-12 00:00:00
2008-09-19 00:00:00
2008-09-26 00:00:00
2008-10-10 00:00:00
2008-10-17 00:00:00
2008-10-24 00:00:00
2008-10-31 00:00:00
2008-11-07 00:00:00
2008-11-14 00:00:00
2008-11-21 00:00:00
2008-11-28 00:00:00
2008-12-05 00:00:00
2008-12-12 00:00:00
2008-12-19 00:00:00
2008-12-26 00:00:00
2009-01-02 00:00:00
2009-01-09 00:00:00
2009-01-16 00:00:00
2009-01-23 00:00:00
2009-02-06 00:00:00
2009-02-13 00:00:00
2009-02-20 00:00:00
2009-02-27 00:00:00
2009-03-06 00:00:00
2009-03-13 00:00:00
2009-03-20 00:00:00
2009-03-27 00:00:00
2009-04-03 00:00:00
2009-04-10 00:00:00
2009-04-17 00:00:00
2009-04-24 00:00:00
2009-05-01 00:00:00
2009-05-08 00:00:00
2009-05-15 00:00:00
2009-05-22 00:00:00
2009-05-29 00:00:00
2009-06-05 00:00:00
2009-06-12 00:00:00
2009-06-19 00:00:00
2009-06-26 00:00:00
2009-07-03 00:00:00
2009-07-10 00:00:00
2009-07-17 00:00:00
2009-07-24 00:00:00
2009-07-31 00:00:00
2009-08-07 00:00:00
2009-08-14 00:00:00
2009-08-21 00:00:00
2009-08-28 00:00:00
2009-09-04 00:00:00
2009-09-11 00:00:00
2009-09-18 00:00:00
2009-09-25 00:00:00
2009-10-02 00:00:00
2009-10-09 00:00:00
2009-10-16 00:00:00
2009-10-23 00:00:00
2009-10-30 00:00:00
2009-11-06 00:00:00
2009-11-13 00:00:00
2009-11-20 00:00:00
2009-11-27 00:00:00
2009-12-04 00:00:00
2009-12-11 00:00:00
2009-12-18 00:00:00
2009-12-25 00:00:00
2010-01-01 00:00:00
2010-01-08 00:00:00
2010-01-15 00:00:00
2010-01-22 00:00:00
2010-01-29 00:00:00
2010-02-05 00:00:00
2010-02-12 00:00:00
2010-02-26 00:00:00
2010-03-05 00:00:00
2010-03-12 00:00:00
2010-03-19 00:00:00
2010-03-26 00:00:00
2010-04-02 00:00:00
2010-04-09 00:00:00
2010-04-16 00:00:00
2010-04-23 00:00:00
2010-04-30 00:00:00
2010-05-07 00:00:00
2010-05-14 00:00:00
2010-05-21 00:00:00
2010-05-28 00:00:00
2010-06-04 00:00:00
2010-06-11 00:00:00
2010-06-18 00:00:00
2010-06-25 00:00:00
2010-07-02 00:00:00
2010-07-09 00:00:00
2010-07-16 00:00:00
2010-07-23 00:00:00
2010-07-30 00:00:00
2010-08-06 00:00:00
2010-08-13 00:00:00
2010-08-20 00:00:00
2010-08-27 00:00:00
2010-09-03 00:00:00
2010-09-10 00:00:00
2010-09-17 00:00:00
2010-09-24 00:00:00
2010-10-01 00:00:00
2010-10-08 00:00:00
2010-10-15 00:00:00
2010-10-22 00:00:00
2010-10-29 00:00:00
2010-11-05 00:00:00
2010-11-12 00:00:00
2010-11-19 00:00:00
2010-11-26 00:00:00
2010-12-03 00:00:00
2010-12-10 00:00:00
2010-12-17 00:00:00
2010-12-24 00:00:00
2010-12-31 00:00:00
2011-01-07 00:00:00
2011-01-14 00:00:00
2011-01-21 00:00:00
2011-01-28 00:00:00
2011-02-04 00:00:00
2011-02-11 00:00:00
2011-02-18 00:00:00
2011-02-25 00:00:00
2011-03-04 00:00:00
2011-03-11 00:00:00
2011-03-18 00:00:00
2011-03-25 00:00:00
2011-04-01 00:00:00
2011-04-08 00:00:00
2011-04-15 00:00:00
2011-04-22 00:00:00
2011-04-29 00:00:00
2011-05-06 00:00:00
2011-05-13 00:00:00
2011-05-20 00:00:00
2011-05-27 00:00:00
2011-06-03 00:00:00
2011-06-10 00:00:00
2011-06-17 00:00:00
2011-06-24 00:00:00
2011-07-01 00:00:00
2011-07-08 00:00:00
2011-07-15 00:00:00
2011-07-22 00:00:00
2011-07-29 00:00:00
2011-08-05 00:00:00
2011-08-12 00:00:00
2011-08-19 00:00:00
2011-08-26 00:00:00
2011-09-02 00:00:00
2011-09-09 00:00:00
2011-09-16 00:00:00
2011-09-23 00:00:00
2011-09-30 00:00:00
2011-10-14 00:00:00
2011-10-21 00:00:00
2011-10-28 00:00:00
2011-11-04 00:00:00
2011-11-11 00:00:00
2011-11-18 00:00:00
2011-11-25 00:00:00
2011-12-02 00:00:00
2011-12-09 00:00:00
2011-12-16 00:00:00
2011-12-23 00:00:00
2011-12-30 00:00:00
2012-01-06 00:00:00
2012-01-13 00:00:00
2012-01-27 00:00:00
2012-02-03 00:00:00
2012-02-10 00:00:00
2012-02-17 00:00:00
2012-02-24 00:00:00
2012-03-02 00:00:00
2012-03-09 00:00:00
2012-03-16 00:00:00
2012-03-23 00:00:00
2012-03-30 00:00:00
2012-04-06 00:00:00
2012-04-13 00:00:00
2012-04-20 00:00:00
2012-04-27 00:00:00
2012-05-04 00:00:00
2012-05-11 00:00:00
2012-05-18 00:00:00
2012-05-25 00:00:00
2012-06-01 00:00:00
2012-06-08 00:00:00
2012-06-15 00:00:00
2012-06-22 00:00:00
2012-06-29 00:00:00
2012-07-06 00:00:00
2012-07-13 00:00:00
2012-07-20 00:00:00
2012-07-27 00:00:00
2012-08-03 00:00:00
2012-08-10 00:00:00
2012-08-17 00:00:00
2012-08-24 00:00:00
2012-08-31 00:00:00
2012-09-07 00:00:00
2012-09-14 00:00:00
2012-09-21 00:00:00
2012-10-05 00:00:00
2012-10-12 00:00:00
2012-10-19 00:00:00
2012-10-26 00:00:00
2012-11-02 00:00:00
2012-11-09 00:00:00
2012-11-16 00:00:00
2012-11-23 00:00:00
2012-11-30 00:00:00
2012-12-07 00:00:00
2012-12-14 00:00:00
2012-12-21 00:00:00
2012-12-28 00:00:00
2013-01-04 00:00:00
2013-01-11 00:00:00
2013-01-18 00:00:00
2013-01-25 00:00:00
2013-02-01 00:00:00
2013-02-08 00:00:00
2013-02-22 00:00:00
2013-03-01 00:00:00
2013-03-08 00:00:00
2013-03-15 00:00:00
2013-03-22 00:00:00
2013-03-29 00:00:00
2013-04-05 00:00:00
2013-04-12 00:00:00
2013-04-19 00:00:00
2013-04-26 00:00:00
2013-05-03 00:00:00
2013-05-10 00:00:00
2013-05-17 00:00:00
2013-05-24 00:00:00
2013-05-31 00:00:00
2013-06-07 00:00:00
2013-06-14 00:00:00
2013-06-21 00:00:00
2013-06-28 00:00:00
2013-07-05 00:00:00
2013-07-12 00:00:00
2013-07-19 00:00:00
2013-07-26 00:00:00
2013-08-02 00:00:00
2013-08-09 00:00:00
2013-08-16 00:00:00
2013-08-23 00:00:00
2013-08-30 00:00:00
2013-09-06 00:00:00
2013-09-13 00:00:00
2013-09-20 00:00:00
2013-09-27 00:00:00
2013-10-04 00:00:00
2013-10-11 00:00:00
2013-10-18 00:00:00
2013-10-25 00:00:00
2013-11-01 00:00:00
2013-11-08 00:00:00
2013-11-15 00:00:00
2013-11-22 00:00:00
2013-11-29 00:00:00
2013-12-06 00:00:00
2013-12-13 00:00:00
2013-12-20 00:00:00
2013-12-27 00:00:00
2014-01-03 00:00:00
2014-01-10 00:00:00
2014-01-17 00:00:00
2014-01-24 00:00:00
2014-01-31 00:00:00
2014-02-07 00:00:00
2014-02-14 00:00:00
2014-02-21 00:00:00
2014-02-28 00:00:00
2014-03-07 00:00:00
2014-03-14 00:00:00
2014-03-21 00:00:00
2014-03-28 00:00:00
2014-04-04 00:00:00
2014-04-11 00:00:00
2014-04-18 00:00:00
2014-04-25 00:00:00
2014-05-02 00:00:00
2014-05-09 00:00:00
2014-05-16 00:00:00
2014-05-23 00:00:00
2014-05-30 00:00:00
2014-06-06 00:00:00
2014-06-13 00:00:00
2014-06-20 00:00:00
2014-06-27 00:00:00
2014-07-04 00:00:00
2014-07-11 00:00:00
2014-07-18 00:00:00
2014-07-25 00:00:00
2014-08-01 00:00:00
2014-08-08 00:00:00
2014-08-15 00:00:00
2014-08-22 00:00:00
2014-08-29 00:00:00
2014-09-05 00:00:00
2014-09-12 00:00:00
2014-09-19 00:00:00
2014-09-26 00:00:00
2014-10-03 00:00:00
2014-10-10 00:00:00
2014-10-17 00:00:00
2014-10-24 00:00:00
2014-10-31 00:00:00
2014-11-07 00:00:00
2014-11-14 00:00:00
2014-11-21 00:00:00
2014-11-28 00:00:00
2014-12-05 00:00:00
2014-12-12 00:00:00
2014-12-19 00:00:00
2014-12-26 00:00:00
2015-01-02 00:00:00
2015-01-09 00:00:00
2015-01-16 00:00:00
2015-01-23 00:00:00
2015-01-30 00:00:00
2015-02-06 00:00:00
2015-02-13 00:00:00
2015-02-20 00:00:00
2015-02-27 00:00:00
2015-03-06 00:00:00
2015-03-13 00:00:00
2015-03-20 00:00:00
2015-03-27 00:00:00
2015-04-03 00:00:00
2015-04-10 00:00:00
2015-04-17 00:00:00

2015-04-24 00:00:00
2015-05-01 00:00:00
2015-05-08 00:00:00
2015-05-15 00:00:00
2015-05-22 00:00:00
2015-05-29 00:00:00
2015-06-05 00:00:00
2015-06-12 00:00:00
2015-06-19 00:00:00
2015-06-26 00:00:00
2015-07-03 00:00:00
2015-07-10 00:00:00
2015-07-17 00:00:00
2015-07-24 00:00:00
2015-07-31 00:00:00
2015-08-07 00:00:00
2015-08-14 00:00:00
2015-08-21 00:00:00
2015-08-28 00:00:00
2015-09-04 00:00:00
2015-09-11 00:00:00
2015-09-18 00:00:00
2015-09-25 00:00:00
2015-10-02 00:00:00
2015-10-09 00:00:00
2015-10-16 00:00:00
2015-10-23 00:00:00
2015-10-30 00:00:00
2015-11-06 00:00:00
2015-11-13 00:00:00
2015-11-20 00:00:00
2015-11-27 00:00:00
2015-12-04 00:00:00
2015-12-11 00:00:00
2015-12-18 00:00:00
2015-12-25 00:00:00
2016-01-01 00:00:00
2016-01-08 00:00:00
2016-01-15 00:00:00
2016-01-22 00:00:00
2016-01-29 00:00:00
2016-02-05 00:00:00
2016-02-19 00:00:00
2016-02-26 00:00:00
2016-03-04 00:00:00
2016-03-11 00:00:00
2016-03-18 00:00:00
2016-03-25 00:00:00
2016-04-01 00:00:00
2016-04-08 00:00:00
2016-04-15 00:00:00
2016-04-22 00:00:00
2016-04-29 00:00:00
2016-05-06 00:00:00
2016-05-13 00:00:00
2016-05-20 00:00:00
2016-05-27 00:00:00
2016-06-03 00:00:00
2016-06-10 00:00:00
2016-06-17 00:00:00
2016-06-24 00:00:00
2016-07-01 00:00:00
2016-07-08 00:00:00
2016-07-15 00:00:00
2016-07-22 00:00:00
2016-07-29 00:00:00
2016-08-05 00:00:00
2016-08-12 00:00:00
2016-08-19 00:00:00
2016-08-26 00:00:00
2016-09-02 00:00:00
2016-09-09 00:00:00
2016-09-16 00:00:00
2016-09-23 00:00:00
2016-09-30 00:00:00
2016-10-14 00:00:00
2016-10-21 00:00:00
2016-10-28 00:00:00
2016-11-04 00:00:00
2016-11-11 00:00:00
2016-11-18 00:00:00
2016-11-25 00:00:00
2016-12-02 00:00:00
2016-12-09 00:00:00
2016-12-16 00:00:00
2016-12-23 00:00:00
2016-12-30 00:00:00
2017-01-06 00:00:00
2017-01-13 00:00:00
2017-01-20 00:00:00
2017-01-27 00:00:00
2017-02-03 00:00:00
2017-02-10 00:00:00
2017-02-17 00:00:00
2017-02-24 00:00:00
2017-03-03 00:00:00
2017-03-10 00:00:00
2017-03-17 00:00:00
2017-03-24 00:00:00
2017-03-31 00:00:00
2017-04-07 00:00:00
2017-04-14 00:00:00
2017-04-21 00:00:00
2017-04-28 00:00:00
2017-05-05 00:00:00
2017-05-12 00:00:00
2017-05-19 00:00:00
2017-05-26 00:00:00
2017-06-02 00:00:00
2017-06-09 00:00:00
2017-06-16 00:00:00
2017-06-23 00:00:00
2017-06-30 00:00:00
2017-07-07 00:00:00
2017-07-14 00:00:00
2017-07-21 00:00:00
2017-07-28 00:00:00
2017-08-04 00:00:00
2017-08-11 00:00:00
2017-08-18 00:00:00
2017-08-25 00:00:00
2017-09-01 00:00:00
2017-09-08 00:00:00
2017-09-15 00:00:00
2017-09-22 00:00:00
2017-10-06 00:00:00
2017-10-13 00:00:00
2017-10-20 00:00:00
2017-10-27 00:00:00
2017-11-03 00:00:00
2017-11-10 00:00:00
2017-11-17 00:00:00
2017-11-24 00:00:00
2017-12-01 00:00:00
2017-12-08 00:00:00
2017-12-15 00:00:00
2017-12-22 00:00:00
2017-12-29 00:00:00
2018-01-05 00:00:00
2018-01-12 00:00:00
2018-01-19 00:00:00
2018-01-26 00:00:00
2018-02-02 00:00:00
2018-02-09 00:00:00
2018-02-16 00:00:00
2018-02-23 00:00:00
2018-03-02 00:00:00
2018-03-09 00:00:00
2018-03-16 00:00:00
2018-03-23 00:00:00
2018-03-30 00:00:00
2018-04-06 00:00:00
2018-04-13 00:00:00
2018-04-20 00:00:00
2018-04-27 00:00:00
2018-05-04 00:00:00
2018-05-11 00:00:00
2018-05-18 00:00:00
2018-05-25 00:00:00
2018-06-01 00:00:00
2018-06-08 00:00:00
2018-06-15 00:00:00
2018-06-22 00:00:00
2018-06-29 00:00:00
2018-07-06 00:00:00
2018-07-13 00:00:00
2018-07-20 00:00:00
2018-07-27 00:00:00
2018-08-03 00:00:00
2018-08-10 00:00:00
2018-08-17 00:00:00
2018-08-24 00:00:00
2018-08-31 00:00:00
2018-09-07 00:00:00
2018-09-14 00:00:00
2018-09-21 00:00:00
2018-10-05 00:00:00
2018-10-12 00:00:00
2018-10-19 00:00:00
2018-10-26 00:00:00
2018-11-02 00:00:00
2018-11-09 00:00:00
2018-11-16 00:00:00
2018-11-23 00:00:00
2018-11-30 00:00:00
2018-12-07 00:00:00
2018-12-14 00:00:00
2018-12-21 00:00:00
2019-01-04 00:00:00
2019-01-11 00:00:00
2019-01-18 00:00:00
2019-01-25 00:00:00
2019-02-01 00:00:00
2019-02-15 00:00:00
2019-02-22 00:00:00
2019-03-01 00:00:00
2019-03-08 00:00:00
2019-03-15 00:00:00
2019-03-22 00:00:00
2019-03-29 00:00:00
2019-04-05 00:00:00
2019-04-12 00:00:00
2019-04-19 00:00:00
2019-04-26 00:00:00
2019-05-03 00:00:00
2019-05-10 00:00:00
2019-05-17 00:00:00
2019-05-24 00:00:00
2019-05-31 00:00:00
2019-06-07 00:00:00
2019-06-14 00:00:00
2019-06-21 00:00:00
2019-06-28 00:00:00
2019-07-05 00:00:00
2019-07-12 00:00:00
2019-07-19 00:00:00
2019-07-26 00:00:00
2019-08-02 00:00:00
2019-08-09 00:00:00
2019-08-16 00:00:00
2019-08-23 00:00:00
2019-08-30 00:00:00
2019-09-06 00:00:00
2019-09-13 00:00:00
2019-09-20 00:00:00
2019-09-27 00:00:00
2019-10-04 00:00:00
2019-10-11 00:00:00
2019-10-18 00:00:00
2019-10-25 00:00:00
2019-11-01 00:00:00
2019-11-08 00:00:00
2019-11-15 00:00:00
2019-11-22 00:00:00
2019-11-29 00:00:00
2019-12-06 00:00:00
2019-12-13 00:00:00
2019-12-20 00:00:00
2019-12-27 00:00:00
2020-01-03 00:00:00
2020-01-10 00:00:00
2020-01-17 00:00:00
2020-01-24 00:00:00
2020-02-07 00:00:00
2020-02-14 00:00:00
2020-02-21 00:00:00
2020-02-28 00:00:00
2020-03-06 00:00:00
2020-03-13 00:00:00
2020-03-20 00:00:00
2020-03-27 00:00:00
2020-04-03 00:00:00
2020-04-10 00:00:00
2020-04-17 00:00:00
2020-04-24 00:00:00
2020-05-01 00:00:00
2020-05-08 00:00:00
2020-05-15 00:00:00
2020-05-22 00:00:00
2020-05-29 00:00:00
2020-06-05 00:00:00
2020-06-12 00:00:00
2020-06-19 00:00:00
2020-06-26 00:00:00
2020-07-03 00:00:00
2020-07-10 00:00:00
2020-07-17 00:00:00
2020-07-24 00:00:00
2020-07-31 00:00:00
2020-08-07 00:00:00
2020-08-14 00:00:00
2020-08-21 00:00:00
2020-08-28 00:00:00
2020-09-04 00:00:00
2020-09-11 00:00:00
2020-09-18 00:00:00
2020-09-25 00:00:00
2020-10-02 00:00:00
2020-10-09 00:00:00
2020-10-16 00:00:00
2020-10-23 00:00:00
2020-10-30 00:00:00
2020-11-06 00:00:00
2020-11-13 00:00:00
2020-11-20 00:00:00
2020-11-27 00:00:00
2020-12-04 00:00:00
2020-12-11 00:00:00
2020-12-18 00:00:00
2020-12-25 00:00:00
2021-01-01 00:00:00
2021-01-08 00:00:00
2021-01-15 00:00:00
2021-01-22 00:00:00
2021-01-29 00:00:00
2021-02-05 00:00:00
2021-02-12 00:00:00
2021-02-19 00:00:00
2021-02-26 00:00:00
2021-03-05 00:00:00
2021-03-12 00:00:00
2021-03-19 00:00:00
2021-03-26 00:00:00
2021-04-02 00:00:00
2021-04-09 00:00:00
2021-04-16 00:00:00
2021-04-23 00:00:00
2021-04-30 00:00:00
2021-05-07 00:00:00
2021-05-14 00:00:00
2021-05-21 00:00:00
2021-05-28 00:00:00
2021-06-04 00:00:00
2021-06-11 00:00:00
2021-06-18 00:00:00
2021-06-25 00:00:00
2021-07-02 00:00:00
2021-07-09 00:00:00
2021-07-16 00:00:00
2021-07-23 00:00:00
2021-07-30 00:00:00
2021-08-06 00:00:00
2021-08-13 00:00:00
2021-08-20 00:00:00
2021-08-27 00:00:00
2021-09-03 00:00:00
2021-09-10 00:00:00
2021-09-17 00:00:00
2021-09-24 00:00:00
2021-10-01 00:00:00
2021-10-08 00:00:00
2021-10-15 00:00:00
2021-10-22 00:00:00
2021-10-29 00:00:00
2021-11-05 00:00:00
2021-11-12 00:00:00
2021-11-19 00:00:00
2021-11-26 00:00:00
2021-12-03 00:00:00
2021-12-10 00:00:00
2021-12-17 00:00:00
2021-12-24 00:00:00
2021-12-31 00:00:00
2022-01-07 00:00:00
2022-01-14 00:00:00
2022-01-21 00:00:00
2022-01-28 00:00:00
2022-02-11 00:00:00
2022-02-18 00:00:00

In [8]:
wbeta

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdwnt,,,,,,,,,,,,,,,,,,,,,
1990-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-14,1.143049,0.726774,NaN,0.96385,1.147328,1.217104,0.443517,0.978206,1.463962,0.537389,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-21,1.138599,0.722725,NaN,0.968259,1.154851,1.217688,0.458787,0.98502,1.470071,0.552696,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-28,1.15734,0.735673,NaN,0.951026,1.116314,1.210972,0.483675,0.975792,1.483434,0.583954,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-11,1.169806,0.741689,NaN,0.98417,1.118438,1.21916,0.478463,0.968829,1.47618,0.596484,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-18,1.189256,0.760826,NaN,0.965901,1.123791,1.213122,0.463827,0.971541,1.46892,0.589758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
wbeta.to_csv('../../Data/factors/beta.csv')

# betasq

In [10]:
sq_wbeta = np.square(wbeta)
sq_wbeta

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdwnt,,,,,,,,,,,,,,,,,,,,,
1990-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-14,1.306561,0.5282,NaN,0.929007,1.316361,1.481343,0.196708,0.956887,2.143184,0.288787,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-21,1.296408,0.522331,NaN,0.937525,1.333682,1.482764,0.210485,0.970265,2.161108,0.305473,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-28,1.339436,0.541215,NaN,0.904451,1.246158,1.466453,0.233942,0.95217,2.200576,0.341003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-11,1.368446,0.550102,NaN,0.96859,1.250903,1.486351,0.228927,0.938629,2.179106,0.355793,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-18,1.414331,0.578856,NaN,0.932964,1.262906,1.471666,0.215135,0.943892,2.157725,0.347814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
sq_wbeta.to_csv('../../Data/factors/betasq.csv')