In [1]:
import my_methods as mm
import pandas as pd
import numpy as np
import datetime as dt
from tqdm import tqdm

# bm
Book-to-market ratio, which equals the book value of equity divided by market capitalization

In [2]:
# 04财务指标分析/FI_T10
# F101001A
df = pd.read_csv('../../Data/raw_data/04财务指标分析/FI_T10.csv')
df = df[df['Stkcd'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

,Stkcd,Accper,Indcd,F100101B,F100102B,F100103C,F100201B,F100202B,F100203C,F100301B,...,F100903A,F100904A,F101001A,F101002A,F101101B,F101201B,F101202B,F101301B,F101302C,Indnme
0,1,1991-12-31,J66,NaN,NaN,NaN,7.911671,7.911671,7.911671,NaN,...,0.622681,0.622681,2.582860,1.605958,NaN,0.0,NaN,NaN,NaN,货币金融服务
1,1,1992-12-31,J66,NaN,NaN,NaN,12.616647,12.616647,12.616647,NaN,...,0.822813,0.822813,2.166351,1.215344,NaN,0.0,0.516184,NaN,NaN,货币金融服务
2,1,1993-12-31,J66,22.031630,22.031630,22.031630,14.763236,14.763236,14.763236,NaN,...,1.517501,1.517501,0.781993,0.658978,NaN,0.0,-0.497753,NaN,NaN,货币金融服务
3,1,1994-06-30,J66,13.249420,NaN,NaN,8.878341,6.094524,8.258889,NaN,...,1.169106,1.169106,0.898933,0.855355,NaN,0.0,-0.398658,NaN,NaN,货币金融服务
4,1,1994-12-31,J66,12.678204,12.678204,12.678204,6.820678,6.820678,6.820678,NaN,...,1.184510,1.184510,0.887088,0.844231,NaN,0.0,-0.531096,NaN,NaN,货币金融服务
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190014,605580,2021-09-30,D44,NaN,28.876078,NaN,NaN,5.111907,NaN,NaN,...,3.844304,3.914019,0.584428,0.260125,NaN,0.0,NaN,12.930371,NaN,电力、热力生产和供应业
190015,605588,2021-09-30,C39,NaN,33.355383,NaN,NaN,2.072407,NaN,NaN,...,2.620094,2.695526,0.711731,0.381666,NaN,0.0,NaN,22.162751,NaN,计算机、通信和其他电子设备制造业
190016,605589,2021-09-30,C26,NaN,32.188856,NaN,NaN,2.732303,NaN,NaN,...,2.162985,2.282368,0.891523,0.462324,NaN,0.0,NaN,20.849752,NaN,化学原料及化学制品制造业
190017,605598,2021-09-30,E48,NaN,29.040716,NaN,NaN,3.305801,NaN,NaN,...,1.650252,1.650864,0.860147,0.605968,NaN,0.0,NaN,22.223376,NaN,土木工程建筑业
190018,605599,2021-09-30,F52,NaN,27.926816,NaN,NaN,1.019648,NaN,NaN,...,2.407159,2.410920,0.876642,0.415428,NaN,0.0,NaN,14.028517,NaN,零售业

In [3]:
bm = df.pivot_table(values='F101001A',index='Accper',columns='Stkcd')
bm

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605488,605499,605500,605507,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,2.582860,0.377695,0.748987,0.778731,NaN,NaN,NaN,NaN,0.443596,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,2.166351,0.386468,0.523175,0.526310,0.636083,0.303976,0.433081,0.376214,0.380138,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,0.781993,0.603225,0.683758,0.725835,0.673882,0.438956,0.536703,0.580065,0.532589,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994-06-30,0.898933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-31,0.997504,1.007400,NaN,0.610773,0.647355,1.017437,0.148290,0.971360,0.839080,0.699459,...,NaN,NaN,0.842368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,0.988221,1.003034,NaN,0.624846,0.663365,1.056557,0.250090,1.015845,0.787128,0.687744,...,NaN,NaN,0.844699,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,0.987092,1.038708,NaN,0.582293,0.839220,1.069528,0.253567,1.026900,0.503450,0.705496,...,0.724538,0.424985,0.884801,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,1.008501,1.057128,NaN,0.596939,0.778340,1.119075,0.256703,1.023545,0.503614,0.746080,...,0.750522,0.465465,0.897683,0.84952,0.953067,0.584428,0.711731,0.891523,0.860147,0.876642
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
    df2 = pd.read_csv('../../Data/raw_data/18年、中、季报基本情况/IAR_Rept.csv')
    df2 = df2[df2['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<= 609999))]
    df2['Accper'] = pd.DatetimeIndex(df2['Accper'])
    df2['Annodt'] = pd.DatetimeIndex(df2['Annodt'])
    df2

,Stkcd,Stknme,Sctcd,Reptyp,Accper,Annodt,Annowk,Annopub,Profita,Profitb,Asseta,Assetb,Erana,Eranb
0,1,深发展A,2,4,1990-12-31,1991-04-30,2,1,NaN,NaN,2.627,NaN,NaN,NaN
1,1,深发展A,2,4,1991-12-31,1992-04-30,4,1,1.126500e+08,NaN,6.406,NaN,NaN,NaN
2,1,深发展A,2,2,1992-06-30,1992-07-28,2,1,9.890000e+07,NaN,NaN,NaN,NaN,NaN
3,1,深发展A,2,4,1992-12-31,1993-02-26,5,1,1.924300e+08,NaN,5.150,NaN,1.39000,NaN
4,1,深发展A,2,2,1993-06-30,1993-08-05,4,1,1.374663e+08,NaN,NaN,NaN,0.55165,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200258,605580,恒盛能源,1,3,2021-09-30,2021-10-30,6,2,8.991872e+07,8.524728e+07,NaN,NaN,0.58000,0.4262
200259,605588,冠石科技,1,3,2021-09-30,2021-10-26,2,2,6.719253e+07,6.153544e+07,NaN,NaN,1.18000,0.8418
200260,605589,圣泉集团,1,3,2021-09-30,2021-10-26,2,2,5.260509e+08,4.471929e+08,NaN,NaN,0.75000,0.5772
200261,605598,上海港湾,1,3,2021-09-30,2021-10-30,6,2,6.696321e+07,6.595164e+07,NaN,NaN,0.52000,0.3818
200262,605599,菜百股份,1,3,2021-09-30,2021-10-28,4,2,2.659621e+08,2.658805e+08,NaN,NaN,0.38000,0.3418

In [4]:
#  将报表会计截止日替换为报表公布日
def change_date(df1, value):
    '''
    df1: old dates that values have,
    df2: old dates mapped to new dates,
    value: values need to be reindexed
    '''
    df2 = pd.read_csv('../../Data/raw_data/18年、中、季报基本情况/IAR_Rept.csv')
    df2 = df2[df2['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<= 609999))]
    df2['Accper'] = pd.DatetimeIndex(df2['Accper'])
    df2['Annodt'] = pd.DatetimeIndex(df2['Annodt'])

    date_change = pd.merge(df1[['Stkcd','Accper']], df2[['Stkcd','Accper','Annodt']], how='inner', on=['Stkcd','Accper'])
    date_change = date_change.sort_values(by='Annodt')
    new_df = pd.DataFrame()
    for index in tqdm(date_change.index):  # 为统一用.loc取元素
        new_df.loc[date_change.loc[index, 'Annodt'], date_change.loc[index, 'Stkcd']] = \
        value.loc[date_change.loc[index, 'Accper'], date_change.loc[index, 'Stkcd']]
    return new_df

bm2 = change_date(df[['Stkcd','Accper']],bm)
bm2

100%|██████████| 164872/164872 [01:30<00:00, 1826.48it/s]

,600601,600656,600654,600653,600602,600651,3,4,1,600652,...,605056,605599,600955,605020,1217,601868,605162,605580,601825,605598
1990-12-31,0.088008,1.052769,0.954035,0.032136,0.871351,0.344861,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,NaN,0.129267,0.895756,0.297951,NaN,0.280724,0.748987,0.778731,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-04-30,0.216023,NaN,NaN,NaN,0.865191,NaN,NaN,NaN,2.58286,0.365254,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,NaN,0.838401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-02-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200610,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-28,NaN,NaN,NaN,NaN,0.724156,NaN,NaN,NaN,NaN,NaN,...,0.771123,0.876642,0.669855,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974707,...,NaN,NaN,NaN,0.633445,0.708572,1.008223,NaN,NaN,NaN,NaN
2021-10-30,0.607054,NaN,0.748010,0.600296,NaN,0.769033,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.625607,0.584428,1.002437,0.860147
2022-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
bm2.to_csv('../../Data/factors/bm.csv')

# bm_ia
This is the industry-adjusted book-to-market ratio

In [6]:
stkcls = pd.read_csv('../../Data/raw_data/05上市公司行业分类表/STK_INDUSTRYCLASS.csv', index_col=[4], parse_dates=True)
stkcls = stkcls[stkcls['IndustryClassificationID'] == 'P0207']  # 证监会2012版分类标准覆盖面最全
stkcls = stkcls[['Symbol','IndustryCode']]
stkcls = stkcls[stkcls['Symbol'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
# 用会计日期对齐的数据进行行业调整，再转化为实际公布日期。但原方法上就存在一个行业中必须所有公司公布报表后才能计算的问题。
bm_ia = mm.industry_adjust_ewa(value_df=bm, industry_df=stkcls)
bm_ia

100%|██████████| 100/100 [03:19<00:00,  2.00s/it]

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605488,605499,605500,605507,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,0.000000,0.000000,0.285040,0.000000,NaN,NaN,NaN,NaN,-0.020351,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,0.000000,-0.098966,-0.052123,0.000000,0.060785,-0.181458,-0.052353,0.000000,-0.195160,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,0.000000,-0.063892,0.064339,0.000000,0.054463,-0.228161,-0.130414,0.046559,-0.086830,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994-06-30,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-31,-0.006219,0.068108,NaN,0.081670,-0.173925,0.078145,-0.791002,0.412983,0.132419,-0.251213,...,NaN,NaN,0.086902,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,-0.015473,0.054840,NaN,0.081665,-0.129316,0.108363,-0.698104,0.402520,0.069367,-0.251657,...,NaN,NaN,0.110134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,-0.020991,0.099755,NaN,0.050935,0.014338,0.130575,-0.685386,0.411420,-0.183591,-0.247431,...,NaN,NaN,0.151266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,0.010029,0.097376,NaN,0.042051,-0.009165,0.159323,-0.703049,0.416869,-0.169786,-0.201087,...,NaN,NaN,0.158724,0.288395,0.044752,-0.228073,0.164075,0.30415,-0.08702,0.085507
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#  将报表会计截止日替换为报表公布日
def change_date(df1, value):
    '''
    df1: old dates that values have,
    df2: old dates mapped to new dates,
    value: values need to be reindexed
    '''
    df2 = pd.read_csv('../../Data/raw_data/18年、中、季报基本情况/IAR_Rept.csv')
    df2 = df2[df2['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<= 609999))]
    df2['Accper'] = pd.DatetimeIndex(df2['Accper'])
    df2['Annodt'] = pd.DatetimeIndex(df2['Annodt'])

    date_change = pd.merge(df1[['Stkcd','Accper']], df2[['Stkcd','Accper','Annodt']], how='inner', on=['Stkcd','Accper'])
    date_change = date_change.sort_values(by='Annodt')
    new_df = pd.DataFrame()
    for index in tqdm(date_change.index):  # 为统一用.loc取元素
        new_df.loc[date_change.loc[index, 'Annodt'], date_change.loc[index, 'Stkcd']] = \
        value.loc[date_change.loc[index, 'Accper'], date_change.loc[index, 'Stkcd']]
    return new_df

bm_ia2 = change_date(df[['Stkcd','Accper']],bm_ia)
bm_ia2

100%|██████████| 164872/164872 [01:30<00:00, 1823.27it/s]

,600601,600656,600654,600653,600602,600651,3,4,1,600652,...,605056,605599,600955,605020,1217,601868,605162,605580,601825,605598
1990-12-31,-0.549790,0.000000,0.316237,-0.234725,0.233553,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,NaN,0.000000,0.236766,-0.165996,NaN,0.000000,0.28504,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-04-30,-0.442967,NaN,NaN,NaN,0.206201,NaN,NaN,NaN,0.0,-0.098693,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,NaN,-0.021352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-02-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.374688,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-28,NaN,NaN,NaN,NaN,0.169268,NaN,NaN,NaN,NaN,NaN,...,-0.070144,0.085507,0.082482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.449299,...,NaN,NaN,NaN,0.046072,0.121199,0.061056,NaN,NaN,NaN,NaN
2021-10-30,0.059398,NaN,0.193122,-0.190839,NaN,0.189409,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.186894,-0.228073,0.003965,-0.08702
2022-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
bm_ia2.to_csv("../../Data/factors/bm_ia.csv")

# cfp
Operating cash flows divided by quarter-end market capitalization. Related data are
contained in quarterly reports and acquired from CSMAR.

In [10]:
# month-end market capitalization
msmvttl = mm.extract_variable_oneFile(filePath='../../Data/raw_data/02月个股回报率/TRD_Mnth.csv',
                                     fileType='csv',
                                     variable='Msmvttl',
                                     time_col='Trdmnt',
                                     code_col='Stkcd')
msmvttl.index = msmvttl.index.to_period('M').to_timestamp('M')
msmvttl

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdmnt,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-31,NaN,5.984896e+05,NaN,185000.00,1446300.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,6.224127e+05,NaN,177125.00,1403100.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,NaN,5.436315e+05,NaN,154750.00,1225800.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,2.118487e+06,4.805241e+05,NaN,139750.00,1082700.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,3.454253e+08,1.925391e+08,NaN,3003058.25,2529903.05,6115477.56,1423901.46,6201173.62,72243783.16,3082653.72,...,16546763.84,NaN,NaN,NaN,6173333.34,3620000.0,3623545.24,26311420.13,NaN,NaN
2021-09-30,3.479481e+08,2.072226e+08,NaN,2960937.43,2233512.74,6061477.76,1465475.23,6256789.53,49469323.85,3017065.34,...,15546469.77,NaN,NaN,NaN,5244444.45,3462000.0,2988310.05,23173574.09,2592879.44,9870000.28
2021-10-31,3.784154e+08,1.770776e+08,NaN,2619290.81,2318195.68,5629479.34,1517442.43,6062133.85,53931364.01,3230227.57,...,14551763.94,6086959.2,3945530.6,2970000.0,5377777.78,3702000.0,2725882.63,23134835.25,2349311.15,9076666.93
2021-11-30,3.384392e+08,1.775638e+08,NaN,2935976.95,2318195.68,5534979.69,2040578.98,6034325.90,45729463.60,3156440.65,...,15848234.46,8674486.8,4022867.8,2988000.0,5666666.67,3482000.0,3217842.68,30518458.15,2532419.23,9636666.94
2021-12-31,3.198095e+08,1.921501e+08,NaN,3029578.76,2434634.74,6020977.91,2109868.59,8175538.32,37218057.51,3090852.27,...,16110881.51,7751184.0,4092204.6,4260000.0,6520000.01,3246000.0,2880853.70,29673951.44,2751803.43,10468889.19

In [15]:
# Operating cash flows
# C001001000 [销售商品、提供劳务收到的现金]
df = pd.read_csv('../../Data/raw_data/15现金流量表（直接法）/FS_Comscfd.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

,Stkcd,Accper,Typrep,C001001000,C0b1002000,C0b1003000,C0b1004000,C0i1005000,C0i1006000,C0i1007000,...,C003005000,C003006000,C003006101,C003007000,C003000000,C004000000,C007000000,C005000000,C005001000,C006000000
1,1,1998-06-30,A,9.671588e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000e+00,NaN,426391.35,3.707121e+07,50108.49,NaN,2.535559e+08,NaN,NaN
2,1,1998-12-31,A,NaN,-7.106518e+08,NaN,4.963261e+08,NaN,NaN,NaN,...,1.594203e+08,4.625089e+06,NaN,NaN,-1.079425e+08,45131.71,NaN,1.158301e+08,4.005841e+08,5.164142e+08
4,1,1999-01-01,A,2.216475e+08,NaN,NaN,-1.769140e+08,NaN,NaN,NaN,...,1.594203e+08,NaN,NaN,4625090.00,-1.079425e+08,45132.00,NaN,NaN,NaN,NaN
6,1,1999-06-30,A,NaN,9.102529e+07,NaN,1.906296e+09,NaN,NaN,NaN,...,2.483850e+07,8.236961e+05,NaN,NaN,-2.566220e+07,-85419.02,NaN,-6.364071e+07,5.164142e+08,4.527735e+08
7,1,1999-12-31,A,NaN,6.580437e+09,86362160.0,NaN,NaN,NaN,NaN,...,6.024658e+07,5.339119e+08,NaN,NaN,-5.941585e+08,99961.00,NaN,2.596769e+09,3.730149e+09,6.326918e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441956,605580,2021-09-30,A,4.465963e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,3.026100e+08,5.277307e+06,NaN,20339909.06,1.991617e+08,NaN,NaN,1.454904e+08,3.272049e+07,1.782109e+08
441957,605588,2021-09-30,A,1.140665e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,8.200000e+07,4.102151e+06,NaN,1927899.56,5.113005e+08,-188988.36,NaN,3.574861e+08,1.441122e+08,5.015982e+08
441958,605589,2021-09-30,A,3.816467e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,1.234609e+09,2.844380e+08,NaN,NaN,2.214140e+09,3372066.23,NaN,-6.053836e+08,1.549205e+09,9.438213e+08
441959,605598,2021-09-30,A,6.498355e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,2.318375e+07,1.302919e+06,NaN,40582498.40,5.578002e+08,-375307.78,NaN,5.779776e+08,2.366865e+08,8.146641e+08
441960,605599,2021-09-30,A,8.038643e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,55353490.34,6.864245e+08,NaN,NaN,5.132572e+08,5.969191e+08,1.110176e+09

In [16]:
oprtcf = df.pivot_table(values='C001001000', index='Accper', columns='Stkcd')
oprtcf

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1998-06-30,9671587.9,NaN,NaN,NaN,1.624538e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-12-31,NaN,2.240218e+09,6.840343e+08,1.077469e+08,4.605739e+07,1.483174e+09,3.181144e+08,8.532144e+07,6.860323e+08,4.136625e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-01-01,221647517.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-06-30,NaN,9.787142e+08,NaN,5.358237e+07,1.411095e+07,NaN,1.372186e+08,9.562825e+07,3.611361e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-31,NaN,2.643205e+09,3.942584e+08,1.361601e+08,6.302805e+07,1.865141e+09,2.131779e+08,4.370849e+07,6.455199e+08,3.989600e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,NaN,1.152944e+11,NaN,2.307571e+07,1.554440e+08,8.046978e+08,1.456973e+07,4.895389e+08,2.755272e+09,3.293133e+08,...,6.535994e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,NaN,2.362905e+11,NaN,8.490358e+07,2.339508e+08,1.638454e+09,5.519025e+07,1.002086e+09,6.043236e+09,4.526097e+08,...,1.378130e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,NaN,3.483900e+11,NaN,1.082342e+08,3.027761e+08,2.594664e+09,1.330316e+08,1.634359e+09,9.684743e+09,5.893526e+08,...,2.226983e+09,1.670474e+09,2.002614e+09,1.687218e+09,1.064058e+09,446596303.7,1.140665e+09,3.816467e+09,6.498355e+08,8.038643e+09
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# 解决'C001001000'中没有当日数据的问题，但其他并列指标有，故df中有。虽然只缺了1997-06-30中一天
accper_date = df[['Stkcd','Accper']]
accper_date = accper_date[accper_date['Accper'].map(lambda x: x in oprtcf.index)]
accper_date

         Stkcd     Accper
1            1 1998-06-30
2            1 1998-12-31
4            1 1999-01-01
6            1 1999-06-30
7            1 1999-12-31
...        ...        ...
441956  605580 2021-09-30
441957  605588 2021-09-30
441958  605589 2021-09-30
441959  605598 2021-09-30
441960  605599 2021-09-30

[195217 rows x 2 columns]

In [34]:
#  将报表会计截止日替换为报表公布日
def change_date(df1, value):
    '''
    df1: old dates that values have,
    df2: old dates mapped to new dates,
    value: values need to be reindexed
    '''
    df2 = pd.read_csv('../../Data/raw_data/18年、中、季报基本情况/IAR_Rept.csv')
    df2 = df2[df2['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<= 609999))]
    df2['Accper'] = pd.DatetimeIndex(df2['Accper'])
    df2['Annodt'] = pd.DatetimeIndex(df2['Annodt'])

    date_change = pd.merge(df1[['Stkcd','Accper']], df2[['Stkcd','Accper','Annodt']], how='inner', on=['Stkcd','Accper'])
    date_change = date_change.sort_values(by='Annodt')
    value = value.reindex(date_change['Stkcd'].drop_duplicates(),axis=1)
    new_df = pd.DataFrame()
    for index in tqdm(date_change.index):  # 为统一用.loc取元素
        new_df.loc[date_change.loc[index, 'Annodt'], date_change.loc[index, 'Stkcd']] = \
        value.loc[date_change.loc[index, 'Accper'], date_change.loc[index, 'Stkcd']]
    return new_df

oprtcf2 = change_date(accper_date,oprtcf)
oprtcf2

100%|██████████| 162765/162765 [01:23<00:00, 1958.43it/s]

,832,600795,600057,600081,600072,600104,729,600076,600752,600059,...,605056,601921,605599,605020,601868,1217,605580,601825,605162,605598
1998-06-30,1.431925e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-07-14,NaN,1.087829e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-07-17,NaN,NaN,6.878129e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-07-18,NaN,NaN,NaN,42447117.18,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-07-20,NaN,NaN,NaN,NaN,1.622509e+08,1.110110e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
# 日期对齐
oprtcf2 = oprtcf2.append(pd.DataFrame(index=msmvttl.index)).sort_index()
oprtcf2 = oprtcf2.fillna(method='ffill')
oprtcf2

,832,600795,600057,600081,600072,600104,729,600076,600752,600059,...,605056,601921,605599,605020,601868,1217,605580,601825,605162,605598
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-28,8.364837e+08,1.277980e+11,3.762310e+11,4.612839e+09,2.388662e+09,5.160286e+11,1.275558e+10,1.311422e+09,69265809.51,1.098009e+09,...,1.368982e+09,7.395517e+09,8.038643e+09,1.546313e+09,1.892716e+11,9.189096e+08,446596303.7,NaN,5.519054e+08,6.498355e+08
2022-01-29,8.364837e+08,1.277980e+11,3.762310e+11,4.612839e+09,2.388662e+09,5.160286e+11,1.275558e+10,1.311422e+09,69265809.51,1.098009e+09,...,1.368982e+09,7.395517e+09,8.038643e+09,1.546313e+09,1.892716e+11,9.189096e+08,446596303.7,NaN,5.519054e+08,6.498355e+08
2022-02-10,8.364837e+08,1.277980e+11,3.762310e+11,4.612839e+09,2.388662e+09,5.160286e+11,1.275558e+10,1.311422e+09,69265809.51,1.098009e+09,...,1.368982e+09,7.395517e+09,8.038643e+09,1.546313e+09,1.892716e+11,9.189096e+08,446596303.7,NaN,5.519054e+08,6.498355e+08
2022-02-15,8.364837e+08,1.277980e+11,3.762310e+11,4.612839e+09,2.388662e+09,5.160286e+11,1.275558e+10,1.311422e+09,69265809.51,1.098009e+09,...,1.368982e+09,7.395517e+09,8.038643e+09,1.546313e+09,1.892716e+11,9.189096e+08,446596303.7,NaN,5.519054e+08,6.498355e+08
2022-02-17,8.364837e+08,1.277980e+11,3.762310e+11,4.612839e+09,2.388662e+09,5.160286e+11,1.275558e+10,1.311422e+09,69265809.51,1.098009e+09,...,1.368982e+09,7.395517e+09,8.038643e+09,1.546313e+09,1.892716e+11,9.189096e+08,446596303.7,NaN,5.519054e+08,6.498355e+08

In [40]:
cfp = oprtcf2 / msmvttl
cfp = cfp.dropna(how='all')
cfp

,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
1998-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-08-31,0.38614,NaN,NaN,NaN,4.578202,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-08-31,0.38614,NaN,NaN,NaN,4.578202,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-31,0.00000,1967.442252,NaN,41.321933,130.608510,460.906588,87.668316,269.601249,179.575340,182.449263,...,114.795274,NaN,NaN,NaN,197.861991,120.636495,418.457111,164.966229,276.606833,885.638178
2021-11-30,0.00000,1962.054951,NaN,36.864785,130.608510,468.775725,65.193077,270.843651,211.783439,186.714311,...,105.404406,NaN,NaN,NaN,187.774909,128.258559,354.481274,125.054369,256.606611,834.172522
2021-11-30,0.00000,1962.054951,NaN,36.864785,130.608510,468.775725,65.193077,270.843651,211.783439,186.714311,...,105.404406,NaN,NaN,NaN,187.774909,128.258559,354.481274,125.054369,256.606611,834.172522
2021-12-31,0.00000,1813.113533,NaN,35.725811,124.362016,430.937325,63.052089,199.908409,260.216242,190.676418,...,103.686054,NaN,NaN,NaN,163.199052,137.583581,395.946858,128.613358,236.148960,767.860144
2021-12-31,0.00000,1813.113533,NaN,35.725811,124.362016,430.937325,63.052089,199.908409,260.216242,190.676418,...,103.686054,NaN,NaN,NaN,163.199052,137.583581,395.946858,128.613358,236.148960,767.860144

In [41]:
cfp.to_csv('../../Data/factors/cfp.csv')

# cfp_ia
This is the industry-adjusted operating cash flows. The way of adjustment is similar to
that for bm ia. Data are acquired from CSMAR.

In [ ]:
stkcls = pd.read_csv('../../Data/raw_data/05上市公司行业分类表/STK_INDUSTRYCLASS.csv', index_col=[4], parse_dates=True)
stkcls = stkcls[stkcls['IndustryClassificationID'] == 'P0207']  # 证监会2012版分类标准覆盖面最全
stkcls = stkcls[['Symbol','IndustryCode']]
stkcls = stkcls[stkcls['Symbol'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
stkcls

In [ ]:
cfp_ia = mm.industry_adjust_ewa(value_df=cfp, industry_df=stkcls)
cfp_ia

In [ ]:
cfp_ia.to_csv('../../Data/factors/cfp_ia.csv')

# sp
Quarterly sales divided by quarter-end market capitalization.

In [ ]:
df = pd.read_csv('../../Data/raw_data/14利润表/FS_Comins.csv')
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

In [ ]:
# B001100000 [营业总收入]
sales = df.pivot_table(values='B001100000', index='Accper', columns='Stkcd')
sales = sales.fillna(method='ffill')
sales

In [ ]:
# month-end market capitalization
msmvttl = mm.extract_variable_oneFile(filePath='D:/csmar解压数据/02月个股回报率/TRD_Mnth.csv',
                                     fileType='csv',
                                     variable='Msmvttl',
                                     time_col='Trdmnt',
                                     code_col='Stkcd')
msmvttl.index = msmvttl.index.to_period('M').to_timestamp('M')
msmvttl

In [ ]:
sp = sales / msmvttl
sp = sp.fillna(method='ffill')
sp

In [ ]:
sp.to_csv('../../Data/factors/sp.csv')

# cashspr
Cash productivity, which is defined as quarter-end market capitalization plus long-term debt minus total assets divided by cash and equivalents. Related data are contained in
quarterly reports and acquired from CSMAR.  
(quarter-end market capitalization + long-term debt - total assets) / cash and equivalents

## 1. market capitalization

In [ ]:
msmvttl = mm.extract_variable_oneFile(filePath='../../Data/raw_data/02月个股回报率/TRD_Mnth.csv',
                                     fileType='csv',
                                     variable='Msmvttl',
                                     time_col='Trdmnt',
                                     code_col='Stkcd')
msmvttl.index = msmvttl.index.to_period('M').to_timestamp('M')
msmvttl

## 2. long-term debt

In [ ]:
# A002206000 [长期负债合计] - 长期负债各项目之合计。1990年起使用，2007年停止使用。
# A002200000 [非流动负债合计] - 所有非流动负债的合计。 2007年起使用。
# 二者拼接起来
# ???为什么这两项时间仍都一直使用
# 决定，只用A002206000 [长期负债合计]
df = pd.read_csv('../../Data/raw_data/16资产负债表/FS_Combas.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

In [ ]:
ltd = df.pivot_table(values='A002206000', index='Accper', columns='Stkcd')
ltd = ltd.replace(0,np.nan)
ltd = ltd.fillna(method='ffill')
ltd

## 3. total assets

In [ ]:
# A001000000 [资产总计] - 资产各项目之总计。1990年起使用
tta = df.pivot_table(values='A001000000', index='Accper', columns='Stkcd')
tta = tta.replace(0,np.nan)
tta = tta.fillna(method='ffill')
tta

## 4. cash and equivalents

In [ ]:
# C006000000 [期末现金及现金等价物余额] - 期末现金及现金等价物的余额.2007年开始使用。
df = pd.read_csv('../../Data/raw_data/15现金流量表（直接法）/FS_Comscfd.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

In [ ]:
cce = df.pivot_table(values='C006000000', index='Accper', columns='Stkcd')
cce = cce.replace(0,np.nan)
cce = cce.fillna(method='ffill')
cce

## 5. results

In [ ]:
cashspr = (msmvttl + ltd - tta) / cce
cashspr = cashspr.loc['1997-06-30':]  # cash and cash equivalent最早在1997-06-30
cashspr = cashspr.fillna(method='ffill')
cashspr

In [ ]:
cashspr.T.to_csv('../../Data/factors/cashspr.csv')

# invest
The sum of annual change in fixed assets and annual change in inventories divided by
lagged total assets.

## 1. annual change in fixed assets

In [ ]:
# A001212000 [固定资产净额] - 固定资产净额为固定资产原价除去累计折旧和固定资产减值准备之后的净额。
df = pd.read_csv('../../Data/raw_data/16资产负债表/FS_Combas.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

In [ ]:
fa = df.pivot_table(values='A001212000', index='Accper', columns='Stkcd')
fa = fa[fa.index.month == 12]
fa

In [ ]:
pct_fa = fa.pct_change(fill_method=None)
pct_fa

## 2. annual change in inventories divided by lagged total assets

In [ ]:
df = pd.read_csv('../../Data/raw_data/16资产负债表/FS_Combas.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

In [ ]:
# A001000000资产总计
tta = df.pivot_table(values='A001000000', index='Accper', columns='Stkcd')
tta = tta[tta.index.month == 12]
tta = tta.replace(0, np.nan)
tta

In [ ]:
# A001123000 [存货净额] - “存货”与“存货跌价准备”之差额。
inventory = df.pivot_table(values='A001123000', index='Accper', columns='Stkcd')
inventory = inventory[inventory.index.month == 12]
inventory = inventory.replace(0, np.nan)
inventory

In [ ]:
inv_by_tta = inventory / tta.shift(1)
inv_by_tta

In [ ]:
pct_inv_by_tta = inv_by_tta.pct_change(fill_method=None)
pct_inv_by_tta

## 3. sum

In [ ]:
invest = pct_fa + pct_inv_by_tta
monthEnd = pd.date_range(start='1990-12-31', end='2022-01-31', freq='m')
invest = invest.reindex(monthEnd)
invest = invest.fillna(method='ffill')
invest.to_csv('../../Data/factors/invest.csv')

# realestate
Investment real estates divided by fixed assets.

In [ ]:
df = pd.read_csv('../../Data/raw_data/16资产负债表/FS_Combas.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
# A001212000 [固定资产净额] - 固定资产净额为固定资产原价除去累计折旧和固定资产减值准备之后的净额。
fa = df.pivot_table(values='A001212000', index='Accper', columns='Stkcd')
fa = fa.fillna(method='ffill')
fa

In [ ]:
# A001211000 [投资性房地产净额]
ire = df.pivot_table(values='A001211000', index='Accper', columns='Stkcd')
ire = ire.fillna(method='ffill')
ire

In [ ]:
realestate = ire / fa
realestate = realestate.fillna(method='ffill')
realestate

In [ ]:
monthEnd = pd.date_range(start='1990-12-31', end='2022-01-31', freq='m')
realestate = realestate.reindex(monthEnd)
realestate = realestate.fillna(method='ffill')
realestate

In [ ]:
realestate.to_csv('../../Data/factors/realestate.csv')

# depr
Depreciation divided by fixed assets.

In [ ]:
# 这张表的csv文件也有问题，故改用excel
df1 = pd.read_excel('../../Data/raw_data/19固定资产、累计折旧、减值准备/FN_Fn020.xlsx')
df2 = pd.read_excel('../../Data/raw_data/19固定资产、累计折旧、减值准备/FN_Fn0201.xlsx')
df = pd.concat([df1, df2])
df

In [ ]:
df = df[df['Stkcd'].map(lambda x: x.startswith('00') or x.startswith('60'))]
df['Stkcd'] = df['Stkcd'].map(lambda x: int(x))
# Typrep [报表类型] - 1、合并会计报表；2、母公司会计报表
df = df[df['Typrep'] == 1]
# Fn02001 [科目类型] - 1、原值；2、累计折旧；3、净值；4、减值准备；5、净额
df = df[df['Fn02001'] == 2]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
# Fn02013 [期末余额] - 固定资产的期末余额
df['Fn02013'] = df['Fn02013'].map(lambda x: float(x))

In [ ]:
depr = df.pivot_table(values='Fn02013', index='Accper', columns='Stkcd')
depr

In [ ]:
df = pd.read_csv('../../Data/raw_data/16资产负债表/FS_Combas.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
# A001212000 [固定资产净额] - 固定资产净额为固定资产原价除去累计折旧和固定资产减值准备之后的净额。
fa = df.pivot_table(values='A001212000', index='Accper', columns='Stkcd')
fa = fa.replace(0,np.nan)
fa

In [ ]:
depr_fa = depr / fa
depr_fa

In [ ]:
depr_fa.iloc[-20:-10]

In [ ]:
depr_fa.to_csv('../../Data/factors/depr.csv')