In [1]:
import my_methods as mm
import pandas as pd
import numpy as np

# 1, mve
mve: Natural log of market capitalization at end of month t − 1. month t is the month to predict

In [2]:
mv = mm.extract_variable_oneFile(filePath='../../Data/raw_data/02月个股回报率/TRD_Mnth.csv', 
                                 fileType='csv',
                                 variable='Msmvttl', 
                                 time_col='Trdmnt', 
                                 code_col='Stkcd')
mv.index = mv.index.to_period('M').to_timestamp('M')  # 快速将月首转到月末
mv

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdmnt,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-31,NaN,5.984896e+05,NaN,185000.00,1446300.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,6.224127e+05,NaN,177125.00,1403100.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,NaN,5.436315e+05,NaN,154750.00,1225800.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,2.118487e+06,4.805241e+05,NaN,139750.00,1082700.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,3.454253e+08,1.925391e+08,NaN,3003058.25,2529903.05,6115477.56,1423901.46,6201173.62,72243783.16,3082653.72,...,16546763.84,NaN,NaN,NaN,6173333.34,3620000.0,3623545.24,26311420.13,NaN,NaN
2021-09-30,3.479481e+08,2.072226e+08,NaN,2960937.43,2233512.74,6061477.76,1465475.23,6256789.53,49469323.85,3017065.34,...,15546469.77,NaN,NaN,NaN,5244444.45,3462000.0,2988310.05,23173574.09,2592879.44,9870000.28
2021-10-31,3.784154e+08,1.770776e+08,NaN,2619290.81,2318195.68,5629479.34,1517442.43,6062133.85,53931364.01,3230227.57,...,14551763.94,6086959.2,3945530.6,2970000.0,5377777.78,3702000.0,2725882.63,23134835.25,2349311.15,9076666.93
2021-11-30,3.384392e+08,1.775638e+08,NaN,2935976.95,2318195.68,5534979.69,2040578.98,6034325.90,45729463.60,3156440.65,...,15848234.46,8674486.8,4022867.8,2988000.0,5666666.67,3482000.0,3217842.68,30518458.15,2532419.23,9636666.94
2021-12-31,3.198095e+08,1.921501e+08,NaN,3029578.76,2434634.74,6020977.91,2109868.59,8175538.32,37218057.51,3090852.27,...,16110881.51,7751184.0,4092204.6,4260000.0,6520000.01,3246000.0,2880853.70,29673951.44,2751803.43,10468889.19

In [3]:
mv_log = np.log(mv)
mv_log

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdmnt,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-31,NaN,13.302164,NaN,12.128111,14.184519,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,13.341359,NaN,12.084611,14.154195,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,NaN,13.206027,NaN,11.949566,14.019104,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,14.566213,13.082633,NaN,11.847610,13.894968,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,19.660287,19.075810,NaN,14.915142,14.743692,15.626333,14.168911,15.640249,18.095557,14.941301,...,16.621701,NaN,NaN,NaN,15.635749,15.101985,15.102963,17.085514,NaN,NaN
2021-09-30,19.667564,19.149304,NaN,14.901016,14.619086,15.617464,14.197690,15.649178,17.716863,14.919795,...,16.559344,NaN,NaN,NaN,15.472680,15.057357,14.910219,16.958523,14.768280,16.105010
2021-10-31,19.751503,18.992099,NaN,14.778414,14.656300,15.543528,14.232537,15.617572,17.803223,14.988063,...,16.493223,15.621659,15.188094,14.904073,15.497786,15.124384,14.818303,16.956850,14.669633,16.021218
2021-11-30,19.639855,18.994841,NaN,14.892551,14.656300,15.526598,14.528744,15.612975,17.638253,14.964956,...,16.578569,15.975897,15.207506,14.910115,15.550112,15.063117,14.984222,17.233842,14.744686,16.081086
2021-12-31,19.583236,19.073788,NaN,14.923934,14.705307,15.610760,14.562136,15.916657,17.432305,14.943957,...,16.595005,15.863356,15.224594,15.264780,15.690385,14.992934,14.873597,17.205780,14.827767,16.163918

In [4]:
mv_log.to_csv('../../Data/factors/mve.csv')

# 2. mve_ia

In [5]:
stkcls = pd.read_csv('../../Data/raw_data/05上市公司行业分类表/STK_INDUSTRYCLASS.csv', index_col=[4], parse_dates=True)
stkcls = stkcls[stkcls['IndustryClassificationID'] == 'P0207']  # 证监会2012版分类标准覆盖面最全
stkcls = stkcls[['Symbol','IndustryCode']]
stkcls = stkcls[stkcls['Symbol'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
stkcls

               Symbol IndustryCode
ImplementDate
1991-04-03          1          J66
1991-01-29          2          K70
1991-07-03          3          S90
1991-01-14          4          G54
2010-08-25          4          C27
...               ...          ...
2021-08-19     605580          D44
2021-08-12     605588          C39
2021-08-10     605589          C26
2021-09-17     605598          E48
2021-09-09     605599          F52

[4567 rows x 2 columns]

In [6]:
mve_ia = mm.industry_adjust_ewa(value_df=mv_log, industry_df=stkcls)
mve_ia

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdmnt,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-31,NaN,0.000000,NaN,0.000000,2.941940,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,0.000000,NaN,0.000000,3.647540,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,NaN,0.000000,NaN,0.000000,3.550361,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,0.000000,0.000000,NaN,0.000000,3.412926,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,1.749032,3.291167,NaN,-0.830659,-0.955972,-0.158310,-1.615732,-0.765176,2.695176,-0.951629,...,0.698923,NaN,NaN,NaN,-0.061181,-1.113645,-0.937299,1.129370,NaN,NaN
2021-09-30,1.755041,3.349419,NaN,-0.845700,-1.147719,-0.182421,-1.602195,-0.694219,2.375783,-1.003928,...,0.622764,NaN,NaN,NaN,-0.220802,-1.377249,-1.076940,1.054045,-1.155444,0.548972
2021-10-31,1.831808,3.253089,NaN,-0.946142,-1.021197,-0.195482,-1.506473,-0.732982,2.493740,-0.848905,...,0.589157,-0.246711,-0.683073,-0.908521,-0.182392,-1.222341,-1.167253,1.085683,-1.167336,0.495365
2021-11-30,1.750537,3.242802,NaN,-0.931532,-1.117798,-0.225440,-1.223295,-0.830767,2.237842,-0.921555,...,0.594887,-0.015122,-0.727830,-0.930633,-0.166910,-1.249847,-1.128932,1.298507,-1.141825,0.533629
2021-12-31,1.684553,3.237591,NaN,-0.945874,-1.092156,-0.225437,-1.274061,-0.557379,2.056523,-0.991968,...,0.511930,-0.100520,-0.729135,-0.667088,-0.178777,-1.421661,-1.250695,1.252051,-1.108159,0.546754

In [7]:
mve_ia.to_csv('../../Data/factors/mve_ia.csv')

# 3. herf
Sum of squared percentage sales in industry for each company. Sales data and industry
code are acquired from CSMAR.  
Sales理解为营业收入

In [39]:
# sum的时间范围是什么？
df = pd.read_csv('../../Data/raw_data/14利润表/FS_Comins.csv')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
df['Accper'] = pd.DatetimeIndex(df['Accper'])
df

,Stkcd,Accper,Typrep,B001100000,B001101000,Bbd1102000,Bbd1102101,Bbd1102203,B0i1103000,B0i1103101,...,B006000102,B001216000,B001211101,B001211203,B001305000,B001302201,B001306000,B001307000,B001308000,B002000301
0,1,1991-12-31,A,3.346900e+08,3.346900e+08,0.000000e+00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1992-12-31,A,4.755108e+08,4.755108e+08,0.000000e+00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1993-06-30,A,2.664955e+08,2.664955e+08,0.000000e+00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1993-12-31,A,4.078706e+08,NaN,3.617215e+08,7.589449e+08,3.972235e+08,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1994-06-30,A,2.970876e+08,NaN,2.787976e+08,4.612229e+08,1.824254e+08,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465487,605580,2021-09-30,A,5.079318e+08,5.079318e+08,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5062385.63,885668.07,7995011.61,NaN,NaN,-3981857.63,1072595.37,NaN
465488,605588,2021-09-30,A,1.081463e+09,1.081463e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,2.266605e+07,4106938.44,654500.08,5054719.67,NaN,NaN,-2500217.31,-15645.79,NaN
465489,605589,2021-09-30,A,6.361000e+09,6.361000e+09,NaN,NaN,NaN,NaN,NaN,...,13175991.09,2.901087e+08,97226241.14,14141176.95,71395803.16,NaN,NaN,37376711.88,673168.38,NaN
465490,605598,2021-09-30,A,5.882567e+08,5.882567e+08,NaN,NaN,NaN,NaN,NaN,...,NaN,7.708755e+06,2890938.40,2591451.61,852154.24,NaN,NaN,22378421.40,-35719.53,NaN
465491,605599,2021-09-30,A,7.259858e+09,7.259858e+09,NaN,NaN,NaN,NaN,NaN,...,-894268.75,3.252396e+06,15083402.02,2418018.01,3372994.74,NaN,NaN,-14559633.18,37149.36,NaN

In [40]:
sales = df.pivot_table(values='B001100000', index='Accper', columns='Stkcd')
sales

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,3.346900e+08,NaN,4.686506e+08,4.987143e+07,NaN,NaN,NaN,NaN,4.090975e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,4.755108e+08,6.613562e+08,7.877559e+08,9.480596e+07,3.786469e+07,1.081658e+08,1.397244e+08,1.403785e+07,7.733561e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,2.664955e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,4.078706e+08,1.084045e+09,1.054117e+09,2.117347e+08,3.406867e+07,1.510638e+08,1.729648e+08,1.457602e+07,9.806126e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,3.827100e+10,6.226410e+10,NaN,3.653115e+07,4.816156e+07,9.182869e+08,1.315511e+07,1.492886e+08,3.715024e+09,2.280631e+08,...,5.536006e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,7.683500e+10,1.671109e+11,NaN,9.301226e+07,1.636117e+08,1.473671e+09,5.495203e+07,5.279869e+08,8.048322e+09,5.629963e+08,...,1.341035e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,1.151080e+11,2.714858e+11,NaN,1.662119e+08,2.919397e+08,2.302271e+09,1.278467e+08,1.042818e+09,1.220675e+10,1.056525e+09,...,2.111076e+09,3.213201e+09,2.225451e+09,1.560928e+09,1.405946e+09,5.079318e+08,1.081463e+09,6.361000e+09,5.882567e+08,7.259858e+09
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
stkcls = pd.read_csv('../../Data/raw_data/05上市公司行业分类表/STK_INDUSTRYCLASS.csv', index_col=[4], parse_dates=True)
stkcls = stkcls[stkcls['IndustryClassificationID'] == 'P0207']  # 证监会2012版分类标准覆盖面最全
stkcls = stkcls[['Symbol','IndustryCode']]
stkcls = stkcls[stkcls['Symbol'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
stkcls

In [42]:
sales_ip = mm.industry_proportion(value_df=sales, industry_df=stkcls)
sales_ip

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,1.000000,NaN,0.523723,1.000000,NaN,NaN,NaN,NaN,0.457172,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,1.000000,0.452158,0.254324,1.000000,0.012224,0.073951,0.095527,1.000000,0.249675,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,1.000000,0.128460,0.131804,1.000000,0.004260,0.017901,0.020497,0.189021,0.122613,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,0.027644,0.130374,NaN,0.000584,0.001543,0.001923,0.000028,0.001321,0.344937,0.000150,...,0.009798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,0.028568,0.133498,NaN,0.000611,0.002309,0.001177,0.000044,0.001910,0.341923,0.000166,...,0.011789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,0.028573,0.144145,NaN,0.000739,0.002606,0.001222,0.000068,0.002476,0.365864,0.000202,...,0.011926,0.005381,NaN,NaN,0.015328,0.00047,0.000527,0.005728,0.000112,0.007179
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
#  将报表会计截止日替换为报表公布日
df2 = pd.read_csv('../../Data/raw_data/18年、中、季报基本情况/IAR_Rept.csv')
df2 = df2[df2['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<= 609999))]
df2['Accper'] = pd.DatetimeIndex(df2['Accper'])
df2['Annodt'] = pd.DatetimeIndex(df2['Annodt'])
df2

,Stkcd,Stknme,Sctcd,Reptyp,Accper,Annodt,Annowk,Annopub,Profita,Profitb,Asseta,Assetb,Erana,Eranb
0,1,深发展A,2,4,1990-12-31,1991-04-30,2,1,NaN,NaN,2.627,NaN,NaN,NaN
1,1,深发展A,2,4,1991-12-31,1992-04-30,4,1,1.126500e+08,NaN,6.406,NaN,NaN,NaN
2,1,深发展A,2,2,1992-06-30,1992-07-28,2,1,9.890000e+07,NaN,NaN,NaN,NaN,NaN
3,1,深发展A,2,4,1992-12-31,1993-02-26,5,1,1.924300e+08,NaN,5.150,NaN,1.39000,NaN
4,1,深发展A,2,2,1993-06-30,1993-08-05,4,1,1.374663e+08,NaN,NaN,NaN,0.55165,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200258,605580,恒盛能源,1,3,2021-09-30,2021-10-30,6,2,8.991872e+07,8.524728e+07,NaN,NaN,0.58000,0.4262
200259,605588,冠石科技,1,3,2021-09-30,2021-10-26,2,2,6.719253e+07,6.153544e+07,NaN,NaN,1.18000,0.8418
200260,605589,圣泉集团,1,3,2021-09-30,2021-10-26,2,2,5.260509e+08,4.471929e+08,NaN,NaN,0.75000,0.5772
200261,605598,上海港湾,1,3,2021-09-30,2021-10-30,6,2,6.696321e+07,6.595164e+07,NaN,NaN,0.52000,0.3818
200262,605599,菜百股份,1,3,2021-09-30,2021-10-28,4,2,2.659621e+08,2.658805e+08,NaN,NaN,0.38000,0.3418

In [46]:
date_change = pd.merge(df[['Stkcd','Accper']], df2[['Stkcd','Accper','Annodt']], how='both', on=['Stkcd','Accper'])
date_change = date_change.sort_values(by='Annodt')
date_change

         Stkcd     Accper     Annodt
158961  600651 1990-12-31 1990-12-31
159553  600656 1990-12-31 1990-12-31
159317  600654 1990-12-31 1990-12-31
153606  600601 1990-12-31 1990-12-31
159198  600653 1990-12-31 1990-12-31
...        ...        ...        ...
67255     2188 2021-12-31 2022-01-29
36980      798 2021-12-31 2022-02-10
102791    2984 2021-12-31 2022-02-15
26774      670 2021-12-31 2022-02-15
60320     2092 2021-12-31 2022-02-17

[169991 rows x 3 columns]

In [51]:
sales_ip2 = pd.DataFrame()
for index in date_change.index :  # 为统一用.loc取元素
    sales_ip2.loc[date_change.loc[index, 'Annodt'], date_change.loc[index, 'Stkcd']] = \
        sales_ip.loc[date_change.loc[index, 'Accper'], date_change.loc[index, 'Stkcd']]
sales_ip2

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Annodt,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,NaN,NaN,0.523723,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-04-30,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.457172,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,NaN,NaN,NaN,NaN,0.012224,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-02-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
sales_ip2.to_csv('../../Data/factors/herf.csv')

# 4. chinv
Change in inventory scaled by total assets.

In [53]:
df = pd.read_csv('../../Data/raw_data/16资产负债表/FS_Combas.csv', index_col='Accper')
df = df[df['Typrep'] == 'A']
df = df[df['Stkcd'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
df.index = pd.DatetimeIndex(df.index)
df

,Stkcd,Typrep,A001101000,A0d1101101,A0d1102000,A0d1102101,A0b1103000,A0b1104000,A0b1105000,A0f1106000,...,A003200000,A003000000,A004000000,A001127000,A001128000,A001226000,A001227000,A001228000,A001229000,A002128000
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,1,A,8.042000e+08,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2.365100e+08,2.919190e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,1,A,3.310000e+07,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,5.779600e+08,4.354460e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,1,A,6.320410e+07,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,5.456622e+08,7.522847e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,1,A,0.000000e+00,NaN,0.0,NaN,NaN,90814922.4,NaN,2.377393e+09,...,NaN,1.189130e+09,9.337871e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994-06-30,1,A,0.000000e+00,NaN,0.0,NaN,1.853747e+09,NaN,NaN,1.324449e+09,...,NaN,1.512913e+09,1.246595e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-30,605580,A,1.782109e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.125735e+08,9.314849e+08,1.260467e+07,NaN,NaN,NaN,NaN,NaN,1.872911e+06
2021-09-30,605588,A,5.131789e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.003418e+08,1.288794e+09,4.095044e+06,NaN,NaN,NaN,4000000.00,NaN,2.522840e+05
2021-09-30,605589,A,1.386646e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.526975e+08,7.930826e+09,1.310657e+10,1.285200e+09,NaN,NaN,NaN,47955396.42,NaN,6.909770e+07
2021-09-30,605598,A,8.450433e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.438024e+09,1.776012e+09,5.000000e+05,2.850373e+08,NaN,NaN,NaN,NaN,3.441598e+07
2021-09-30,605599,A,1.255342e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.078357e+07,3.110357e+09,4.803754e+09,NaN,NaN,NaN,NaN,NaN,NaN,3.417211e+08

In [54]:
total_assets = df.pivot_table(values='A001000000', index='Accper', columns='Stkcd')  # A001000000资产总计
total_assets = total_assets.replace(0,np.nan)
total_assets

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,2.919190e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,4.354460e+09,5.684941e+08,6.078172e+08,1.340786e+08,NaN,NaN,NaN,NaN,6.642928e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,7.522847e+09,9.455016e+08,1.018333e+09,3.224412e+08,6.138121e+08,2.288015e+08,1.322528e+08,1.082672e+08,1.546114e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,9.337871e+09,2.136159e+09,1.921612e+09,7.718936e+08,6.920086e+08,5.557977e+08,3.135394e+08,2.408760e+08,3.270337e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,4.572974e+12,1.907860e+12,NaN,1.579540e+09,2.404022e+09,1.605208e+10,3.789513e+08,1.317685e+10,3.223258e+10,3.558606e+09,...,2.400768e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,4.723520e+12,1.955046e+12,NaN,1.556155e+09,2.426484e+09,1.876161e+10,4.098859e+08,1.274585e+10,3.305083e+10,3.731692e+09,...,2.523014e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,4.853074e+12,1.967403e+12,NaN,1.623624e+09,2.485983e+09,1.981674e+10,4.286182e+08,1.317730e+10,3.436544e+10,4.039276e+09,...,2.588452e+09,7.710989e+09,2.392599e+09,1.672137e+09,4.828118e+09,9.314849e+08,1.288794e+09,1.310657e+10,1.776012e+09,4.803754e+09
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
inventory = df.pivot_table(values='A001123000', index='Accper', columns='Stkcd')
# A001123000 [存货净额] - “存货”与“存货跌价准备”之差额。
inventory = inventory.replace(0,np.nan)
inventory

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,NaN,1.411705e+08,6.724117e+07,2280080.10,NaN,NaN,NaN,NaN,1.944474e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,NaN,2.198933e+08,2.855731e+08,7578034.56,59987113.41,9.659121e+07,50356327.68,1.130758e+04,1.967769e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,NaN,5.701639e+08,4.048913e+08,15933921.87,60521288.93,1.005085e+08,57438952.24,2.857923e+04,7.607489e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994-12-31,4.816629e+08,8.670936e+08,9.004814e+08,19534163.73,34823956.76,1.237468e+08,52528365.32,3.506737e+06,1.052635e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,NaN,1.020764e+12,NaN,4911172.57,20995352.69,7.536558e+09,1392682.49,1.253411e+09,8.971729e+09,1.852698e+08,...,2.543482e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,NaN,1.047878e+12,NaN,NaN,16713696.24,1.071061e+10,13260341.79,1.316003e+09,8.701579e+09,1.911843e+08,...,2.179284e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,NaN,1.112923e+12,NaN,NaN,18526973.99,1.277117e+10,18542206.36,1.305964e+09,1.032174e+10,2.002814e+08,...,2.490589e+08,1.218768e+09,3.202884e+08,2.908221e+08,1.956748e+08,17834405.81,1.145105e+08,1.481173e+09,62283507.4,1.867700e+09
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
inventory_by_assets = inventory / total_assets
inventory_by_assets = inventory_by_assets.replace(np.inf, np.nan)
inventory_by_assets

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,NaN,0.248324,0.110627,0.017006,NaN,NaN,NaN,NaN,0.292713,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,NaN,0.232568,0.280432,0.023502,0.097729,0.422162,0.380758,0.000104,0.127272,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,NaN,0.266911,0.210704,0.020643,0.087457,0.180836,0.183195,0.000119,0.232621,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,NaN,0.535031,NaN,0.003109,0.008733,0.469507,0.003675,0.095122,0.278344,0.052062,...,0.105944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,NaN,0.535986,NaN,NaN,0.006888,0.570879,0.032351,0.103250,0.263279,0.051233,...,0.086376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,NaN,0.565681,NaN,NaN,0.007453,0.644464,0.043260,0.099107,0.300352,0.049583,...,0.096219,0.158056,0.133866,0.173922,0.040528,0.019146,0.088851,0.11301,0.035069,0.3888
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
pct_inventory_by_assets = inventory_by_assets.pct_change()
pct_inventory_by_assets = pct_inventory_by_assets.replace(0,np.nan)
pct_inventory_by_assets

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,NaN,-0.063448,1.534925,0.382023,NaN,NaN,NaN,NaN,-0.565199,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,NaN,0.147669,-0.248645,-0.121667,-0.105101,-0.571642,-0.518867,0.136016,0.827748,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,NaN,-0.001992,NaN,-0.010115,0.585966,-0.070724,-0.059833,0.126359,0.039018,-0.096263,...,0.552303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,NaN,0.001786,NaN,NaN,-0.211303,0.215912,7.802845,0.085442,-0.054123,-0.015940,...,-0.184703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,NaN,0.055403,NaN,NaN,0.081961,0.128898,0.337208,-0.040121,0.140815,-0.032189,...,0.113955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
pct_inventory_by_assets.to_csv('../../Data/factors/chinv.csv')

# 5. chcsho
Monthly percentage change in shares outstanding.  
Outstanding shares = 股东持有的股票+限售股(restricted shares)  
Issued shares = Outstanding shares + 库存股(treasury shares)  
就理解为股本变动中的总股数吧

In [60]:
# D:\csmar解压数据\17股本变动
# Nshrttl [总股数]

In [61]:
df = pd.read_csv('../../Data/raw_data/17股本变动/TRD_Capchg.csv', index_col='Shrchgdt')
df = df[df['Stkcd'].map(lambda x: (x>=0 and x<=9999) or (x>=600000 and x<=609999))]
df.index = pd.DatetimeIndex(df.index)
df

,Stkcd,Shrtyp,Nshrttl,Nshrstt,Nshrlpd,Nshrlpf,Nshrlpn,Nshremp,Nshrmf,Nshrrot,Nshrprf,Nshra,Nshrb,Nshrh,Nshrunl,Nshrsms,Nshrglea,Nshrsina,Nshrlpo,Nshroft
Shrchgdt,,,,,,,,,,,,,,,,,,,,
1991-04-03,1,10000,48500171.0,22000171.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1991-08-01,1,100,89751643.0,7787387.0,0.0,0.0,22309116.0,14666219.0,0.0,0.0,0.0,44988921.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1992-03-23,1,3000,134696625.0,11687081.0,0.0,0.0,33480865.0,22010630.0,0.0,0.0,0.0,67518049.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1993-05-24,1,3100,269417899.0,21620134.0,0.0,0.0,61939600.0,40719665.0,0.0,0.0,0.0,145138500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1994-06-30,1,20008,269417899.0,21621080.0,0.0,0.0,61939568.0,6735000.0,0.0,0.0,0.0,179122251.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-19,605580,10000,200000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50000000.0,0.0,0.0,0.0,107660000.0,0.0,0.0,42340000.0,0.0
2021-08-12,605588,10000,73099561.0,0.0,7074561.0,0.0,0.0,0.0,0.0,0.0,0.0,18275000.0,0.0,0.0,0.0,47750000.0,0.0,0.0,0.0,0.0
2021-08-10,605589,10000,774776800.0,0.0,133703300.0,0.0,0.0,0.0,0.0,0.0,0.0,81060000.0,0.0,0.0,0.0,192908900.0,0.0,0.0,367104600.0,0.0
2021-09-17,605598,10000,172743467.0,0.0,129450000.0,0.0,0.0,0.0,0.0,0.0,0.0,43193467.0,0.0,0.0,0.0,100000.0,0.0,0.0,0.0,0.0
2021-09-09,605599,10000,777777800.0,218400000.0,350451818.0,0.0,0.0,0.0,0.0,0.0,0.0,77777800.0,0.0,0.0,0.0,49548728.0,0.0,0.0,81599454.0,0.0

In [62]:
shares = df.pivot_table(values='Nshrttl', index='Shrchgdt', columns='Stkcd')
shares

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Shrchgdt,,,,,,,,,,,,,,,,,,,,,
1990-12-10,NaN,NaN,NaN,NaN,90000000.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-14,NaN,NaN,NaN,12500000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-29,NaN,41246700.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-03,48500171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-02-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
pct_shares = shares.pct_change()
pct_shares = pct_shares.replace(0, np.nan)
pct_shares

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Shrchgdt,,,,,,,,,,,,,,,,,,,,,
1990-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-02-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
pct_shares.to_csv('../../Data/factors/chcsho.csv')

# deprecated
outstanding shares = issued shares - treasury shares

## treasury share

In [ ]:
df = pd.read_csv('D:/csmar解压数据/16资产负债表/FS_Combas.csv', index_col='Accper')
df = df[df['Typrep'] == 'A']
f = lambda x: True if (x>=0 and x<=9999) or (x>=600000 and x<=609999) else False
df = df[df['Stkcd'].map(f)]
df.index = pd.DatetimeIndex(df.index)
df

In [ ]:
treasury_share = df.pivot_table(values='A003102101', index='Accper', columns='Stkcd')
# A003102101 [其中：库存股] - 企业收购、转让或注销的本公司股份金额。
treasury_share

In [ ]:
m_s = pd.date_range(start='1990-01-31', end='2021-12-31', freq='M')
treasury_share = treasury_share.asfreq('M').reindex(m_s).fillna(method='ffill').replace(np.nan, 0.0)
treasury_share

## issued share

In [ ]:
df = pd.read_csv('D:/csmar解压数据/17股本变动/TRD_Capchg.csv', index_col='Shrchgdt')
f = lambda x: True if (x>=0 and x<=9999) or (x>=600000 and x<=609999) else False
df = df[df['Stkcd'].map(f)]
df.index = pd.DatetimeIndex(df.index)
df

In [ ]:
issued_share = df.pivot_table(values='Nshrttl', index='Shrchgdt', columns='Stkcd')
issued_share

In [ ]:
m_s = pd.date_range(start='1990-01-31', end='2021-12-31', freq='M')
m_s

In [ ]:
new_index = issued_share.index.append(m_s).sort_values().drop_duplicates()
new_index

In [ ]:
issued_share = issued_share.reindex(new_index).fillna(method='ffill')
issued_share

In [ ]:
issued_share = issued_share.loc[m_s]
issued_share

In [ ]:
outstanding_share = issued_share - treasury_share
outstanding_share

In [ ]:
# 有负数，大概有五六十个，但我不知道怎么回事
outstanding_share.applymap(lambda x: True if x < 0 else False).any().any()

In [ ]:
outstanding_share.T.to_csv('C:/Users/ShaunMarx/助研_人大/project01_China_stock/Data/factors/chcsho.csv')