In [10]:
import my_methods as mm
import pandas as pd
import numpy as np
import datetime as dt
from sklearn.linear_model import LinearRegression

# idiovol
Standard deviation of residuals of weekly returns on weekly equally-weighted market
returns for three years prior to month end.

In [11]:
df1 = pd.read_csv('../../Data/raw_data/12周个股回报率/TRD_Week.csv')
df2 = pd.read_csv('../../Data/raw_data/12周个股回报率/TRD_Week1.csv')
df3 = pd.read_csv('../../Data/raw_data/12周个股回报率/TRD_Week2.csv')
df = pd.concat([df1,df2,df3])
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df

,Stkcd,Trdwnt,Opndt,Wopnprc,Clsdt,Wclsprc,Wnshrtrd,Wnvaltrd,Wsmvosd,Wsmvttl,Ndaytrd,Wretwd,Wretnd,Markettype,Capchgdt,Ahshrtrd_W,Ahvaltrd_W
0,1,1991-14,1991-04-03,49.00,1991-04-06,48.28,1300,64000.0,1279420.00,2341588.26,4,NaN,NaN,4,1991-04-03,NaN,NaN
1,1,1991-15,1991-04-08,48.04,1991-04-13,46.84,3400,161000.0,1241260.00,2271748.01,5,-0.029826,-0.029826,4,1991-04-03,NaN,NaN
2,1,1991-16,1991-04-16,46.38,1991-04-20,45.46,1400,64000.0,1204690.00,2204817.77,5,-0.029462,-0.029462,4,1991-04-03,NaN,NaN
3,1,1991-17,1991-04-23,45.00,1991-04-26,44.34,6700,300000.0,1175010.00,2150497.58,4,-0.024637,-0.024637,4,1991-04-03,NaN,NaN
4,1,1991-18,1991-04-29,43.90,1991-05-04,43.02,1300,57000.0,1140030.00,2086477.36,5,-0.029770,0.365088,4,1991-04-03,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655361,605599,2022-03,2022-01-10,13.71,2022-01-14,13.89,61071792,868917660.0,1080333.64,10803333.64,5,-0.000719,-0.000719,1,2021-09-09,0.0,0.0
655362,605599,2022-04,2022-01-17,13.76,2022-01-21,13.15,30112749,404360677.0,1022778.07,10227778.07,5,-0.053276,-0.053276,1,2021-09-09,0.0,0.0
655363,605599,2022-05,2022-01-24,13.19,2022-01-28,11.89,23896420,300780958.0,924778.04,9247778.04,5,-0.095817,-0.095817,1,2021-09-09,0.0,0.0
655364,605599,2022-07,2022-02-07,13.08,2022-02-11,12.63,64437261,859338170.0,982333.61,9823333.61,5,0.062237,0.062237,1,2021-09-09,0.0,0.0
655365,605599,2022-08,2022-02-14,12.88,2022-02-18,12.41,33646695,426113969.0,965222.50,9652222.50,5,-0.017419,-0.017419,1,2021-09-09,0.0,0.0

In [12]:
df['Trdwnt'] = pd.to_datetime([x+'-5' for x in df['Trdwnt']], format='%Y-%W-%w') - pd.DateOffset(days=7)
df

,Stkcd,Trdwnt,Opndt,Wopnprc,Clsdt,Wclsprc,Wnshrtrd,Wnvaltrd,Wsmvosd,Wsmvttl,Ndaytrd,Wretwd,Wretnd,Markettype,Capchgdt,Ahshrtrd_W,Ahvaltrd_W
0,1,1991-04-05,1991-04-03,49.00,1991-04-06,48.28,1300,64000.0,1279420.00,2341588.26,4,NaN,NaN,4,1991-04-03,NaN,NaN
1,1,1991-04-12,1991-04-08,48.04,1991-04-13,46.84,3400,161000.0,1241260.00,2271748.01,5,-0.029826,-0.029826,4,1991-04-03,NaN,NaN
2,1,1991-04-19,1991-04-16,46.38,1991-04-20,45.46,1400,64000.0,1204690.00,2204817.77,5,-0.029462,-0.029462,4,1991-04-03,NaN,NaN
3,1,1991-04-26,1991-04-23,45.00,1991-04-26,44.34,6700,300000.0,1175010.00,2150497.58,4,-0.024637,-0.024637,4,1991-04-03,NaN,NaN
4,1,1991-05-03,1991-04-29,43.90,1991-05-04,43.02,1300,57000.0,1140030.00,2086477.36,5,-0.029770,0.365088,4,1991-04-03,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655361,605599,2022-01-14,2022-01-10,13.71,2022-01-14,13.89,61071792,868917660.0,1080333.64,10803333.64,5,-0.000719,-0.000719,1,2021-09-09,0.0,0.0
655362,605599,2022-01-21,2022-01-17,13.76,2022-01-21,13.15,30112749,404360677.0,1022778.07,10227778.07,5,-0.053276,-0.053276,1,2021-09-09,0.0,0.0
655363,605599,2022-01-28,2022-01-24,13.19,2022-01-28,11.89,23896420,300780958.0,924778.04,9247778.04,5,-0.095817,-0.095817,1,2021-09-09,0.0,0.0
655364,605599,2022-02-11,2022-02-07,13.08,2022-02-11,12.63,64437261,859338170.0,982333.61,9823333.61,5,0.062237,0.062237,1,2021-09-09,0.0,0.0
655365,605599,2022-02-18,2022-02-14,12.88,2022-02-18,12.41,33646695,426113969.0,965222.50,9652222.50,5,-0.017419,-0.017419,1,2021-09-09,0.0,0.0

In [13]:
stk_wret = df.pivot_table(values='Wretwd', index='Trdwnt', columns='Stkcd')
stk_wret

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdwnt,,,,,,,,,,,,,,,,,,,,,
1990-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-11,NaN,NaN,NaN,NaN,-0.032169,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-18,NaN,NaN,NaN,NaN,-0.023496,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-14,-0.050581,-0.054363,NaN,0.027936,-0.004329,-0.022026,-0.032544,-0.034965,0.036638,0.000000,...,-0.007722,0.013539,-0.012342,0.190526,0.039273,-0.008997,-0.005851,-0.009187,-0.133755,-0.000719
2022-01-21,0.062462,0.045411,NaN,-0.027176,-0.082609,0.015766,0.045872,-0.043478,-0.024948,-0.041667,...,-0.020752,-0.036145,-0.050321,-0.170092,-0.102869,-0.056420,-0.037871,0.000281,-0.108366,-0.053276
2022-01-28,-0.087608,-0.060536,NaN,-0.011837,0.014218,-0.048780,-0.068713,-0.034091,-0.089552,-0.086957,...,0.065563,-0.039946,-0.039829,-0.154373,-0.039002,-0.057732,-0.058245,-0.098034,-0.074937,-0.095817
2022-02-11,0.080227,0.041810,NaN,0.145664,0.037383,0.062937,-0.001570,0.000000,0.025761,0.062500,...,-0.027346,-0.057458,0.029630,-0.003738,0.138799,0.025529,0.017227,0.010900,0.157931,0.062237
2022-02-18,-0.019298,-0.033050,NaN,-0.079046,0.009009,-0.006579,0.042453,0.129412,0.062405,0.075630,...,-0.093610,0.034535,0.001439,-0.016260,-0.027085,0.009246,0.018323,0.023721,0.019988,-0.017419

In [14]:
df = pd.read_csv('../../Data/raw_data/13周市场回报率/TRD_Weekcm.csv', index_col='Trdwnt')
mkt_wret = df[df['Markettype'] == 5]['Cwretwdeq']  # equally-weighted market returns
mkt_wret

Trdwnt
1990-51         NaN
1990-52    0.132329
1990-53    0.010005
1991-01    0.026998
1991-02    0.011304
             ...
2022-03    0.000127
2022-04   -0.027511
2022-05   -0.052635
2022-07    0.031713
2022-08    0.018916
Name: Cwretwdeq, Length: 1590, dtype: float64

In [15]:
mkt_wret.index = pd.to_datetime([x+'-5' for x in mkt_wret.index], format='%Y-%W-%w') - pd.DateOffset(days=7)
mkt_wret

1990-12-14         NaN
1990-12-21    0.132329
1990-12-28    0.010005
1991-01-04    0.026998
1991-01-11    0.011304
                ...
2022-01-14    0.000127
2022-01-21   -0.027511
2022-01-28   -0.052635
2022-02-11    0.031713
2022-02-18    0.018916
Name: Cwretwdeq, Length: 1590, dtype: float64

In [16]:
month_ends = pd.date_range(start='1990-12-31', end='2021-01-31', freq='M')
month_ends

DatetimeIndex(['1990-12-31', '1991-01-31', '1991-02-28', '1991-03-31',
               '1991-04-30', '1991-05-31', '1991-06-30', '1991-07-31',
               '1991-08-31', '1991-09-30',
               ...
               '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31',
               '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30',
               '2020-12-31', '2021-01-31'],
              dtype='datetime64[ns]', length=362, freq='M')

In [18]:
model = LinearRegression()
idiovol = pd.DataFrame(columns=stk_wret.columns, index=month_ends)
for endday in month_ends:
    print(endday)
    beginday = endday - pd.DateOffset(years=3)
    stk_sec = stk_wret.loc[beginday:endday]
    for stock in stk_wret.columns:
        y = stk_sec.loc[:, stock]
        x = mkt_wret[beginday:endday]
        temp_df = pd.concat([y, x], axis=1).dropna()
        if len(temp_df) <=52:
            continue
        X = temp_df.iloc[:,[1]].to_numpy()
        y = temp_df.iloc[:,0].to_numpy()
        model.fit(X=X, y=y)      
        idiovol.loc[endday, stock] = np.std(y - model.predict(X))

1990-12-31 00:00:00
1991-01-31 00:00:00
1991-02-28 00:00:00
1991-03-31 00:00:00
1991-04-30 00:00:00
1991-05-31 00:00:00
1991-06-30 00:00:00
1991-07-31 00:00:00
1991-08-31 00:00:00
1991-09-30 00:00:00
1991-10-31 00:00:00
1991-11-30 00:00:00
1991-12-31 00:00:00
1992-01-31 00:00:00
1992-02-29 00:00:00
1992-03-31 00:00:00
1992-04-30 00:00:00
1992-05-31 00:00:00
1992-06-30 00:00:00
1992-07-31 00:00:00
1992-08-31 00:00:00
1992-09-30 00:00:00
1992-10-31 00:00:00
1992-11-30 00:00:00
1992-12-31 00:00:00
1993-01-31 00:00:00
1993-02-28 00:00:00
1993-03-31 00:00:00
1993-04-30 00:00:00
1993-05-31 00:00:00
1993-06-30 00:00:00
1993-07-31 00:00:00
1993-08-31 00:00:00
1993-09-30 00:00:00
1993-10-31 00:00:00
1993-11-30 00:00:00
1993-12-31 00:00:00
1994-01-31 00:00:00
1994-02-28 00:00:00
1994-03-31 00:00:00
1994-04-30 00:00:00
1994-05-31 00:00:00
1994-06-30 00:00:00
1994-07-31 00:00:00
1994-08-31 00:00:00
1994-09-30 00:00:00
1994-10-31 00:00:00
1994-11-30 00:00:00
1994-12-31 00:00:00
1995-01-31 00:00:00
1995-02-28 00:00:00
1995-03-31 00:00:00
1995-04-30 00:00:00
1995-05-31 00:00:00
1995-06-30 00:00:00
1995-07-31 00:00:00
1995-08-31 00:00:00
1995-09-30 00:00:00
1995-10-31 00:00:00
1995-11-30 00:00:00
1995-12-31 00:00:00
1996-01-31 00:00:00
1996-02-29 00:00:00
1996-03-31 00:00:00
1996-04-30 00:00:00
1996-05-31 00:00:00
1996-06-30 00:00:00
1996-07-31 00:00:00
1996-08-31 00:00:00
1996-09-30 00:00:00
1996-10-31 00:00:00
1996-11-30 00:00:00
1996-12-31 00:00:00
1997-01-31 00:00:00
1997-02-28 00:00:00
1997-03-31 00:00:00
1997-04-30 00:00:00
1997-05-31 00:00:00
1997-06-30 00:00:00
1997-07-31 00:00:00
1997-08-31 00:00:00
1997-09-30 00:00:00
1997-10-31 00:00:00
1997-11-30 00:00:00
1997-12-31 00:00:00
1998-01-31 00:00:00
1998-02-28 00:00:00
1998-03-31 00:00:00
1998-04-30 00:00:00
1998-05-31 00:00:00
1998-06-30 00:00:00
1998-07-31 00:00:00
1998-08-31 00:00:00
1998-09-30 00:00:00
1998-10-31 00:00:00
1998-11-30 00:00:00
1998-12-31 00:00:00
1999-01-31 00:00:00
1999-02-28 00:00:00
1999-03-31 00:00:00
1999-04-30 00:00:00
1999-05-31 00:00:00
1999-06-30 00:00:00
1999-07-31 00:00:00
1999-08-31 00:00:00
1999-09-30 00:00:00
1999-10-31 00:00:00
1999-11-30 00:00:00
1999-12-31 00:00:00
2000-01-31 00:00:00
2000-02-29 00:00:00
2000-03-31 00:00:00
2000-04-30 00:00:00
2000-05-31 00:00:00
2000-06-30 00:00:00
2000-07-31 00:00:00
2000-08-31 00:00:00
2000-09-30 00:00:00
2000-10-31 00:00:00
2000-11-30 00:00:00
2000-12-31 00:00:00
2001-01-31 00:00:00
2001-02-28 00:00:00
2001-03-31 00:00:00
2001-04-30 00:00:00
2001-05-31 00:00:00
2001-06-30 00:00:00
2001-07-31 00:00:00
2001-08-31 00:00:00
2001-09-30 00:00:00
2001-10-31 00:00:00
2001-11-30 00:00:00
2001-12-31 00:00:00
2002-01-31 00:00:00
2002-02-28 00:00:00
2002-03-31 00:00:00
2002-04-30 00:00:00
2002-05-31 00:00:00
2002-06-30 00:00:00
2002-07-31 00:00:00
2002-08-31 00:00:00
2002-09-30 00:00:00
2002-10-31 00:00:00
2002-11-30 00:00:00
2002-12-31 00:00:00
2003-01-31 00:00:00
2003-02-28 00:00:00
2003-03-31 00:00:00
2003-04-30 00:00:00
2003-05-31 00:00:00
2003-06-30 00:00:00
2003-07-31 00:00:00
2003-08-31 00:00:00
2003-09-30 00:00:00
2003-10-31 00:00:00
2003-11-30 00:00:00
2003-12-31 00:00:00
2004-01-31 00:00:00
2004-02-29 00:00:00
2004-03-31 00:00:00
2004-04-30 00:00:00
2004-05-31 00:00:00
2004-06-30 00:00:00
2004-07-31 00:00:00
2004-08-31 00:00:00
2004-09-30 00:00:00
2004-10-31 00:00:00
2004-11-30 00:00:00
2004-12-31 00:00:00
2005-01-31 00:00:00
2005-02-28 00:00:00
2005-03-31 00:00:00
2005-04-30 00:00:00
2005-05-31 00:00:00
2005-06-30 00:00:00
2005-07-31 00:00:00
2005-08-31 00:00:00
2005-09-30 00:00:00
2005-10-31 00:00:00
2005-11-30 00:00:00
2005-12-31 00:00:00
2006-01-31 00:00:00
2006-02-28 00:00:00
2006-03-31 00:00:00
2006-04-30 00:00:00
2006-05-31 00:00:00
2006-06-30 00:00:00
2006-07-31 00:00:00
2006-08-31 00:00:00
2006-09-30 00:00:00
2006-10-31 00:00:00
2006-11-30 00:00:00
2006-12-31 00:00:00
2007-01-31 00:00:00
2007-02-28 00:00:00
2007-03-31 00:00:00
2007-04-30 00:00:00
2007-05-31 00:00:00
2007-06-30 00:00:00
2007-07-31 00:00:00
2007-08-31 00:00:00
2007-09-30 00:00:00
2007-10-31 00:00:00
2007-11-30 00:00:00
2007-12-31 00:00:00
2008-01-31 00:00:00
2008-02-29 00:00:00
2008-03-31 00:00:00
2008-04-30 00:00:00
2008-05-31 00:00:00
2008-06-30 00:00:00
2008-07-31 00:00:00
2008-08-31 00:00:00
2008-09-30 00:00:00
2008-10-31 00:00:00
2008-11-30 00:00:00
2008-12-31 00:00:00
2009-01-31 00:00:00
2009-02-28 00:00:00
2009-03-31 00:00:00
2009-04-30 00:00:00
2009-05-31 00:00:00
2009-06-30 00:00:00
2009-07-31 00:00:00
2009-08-31 00:00:00
2009-09-30 00:00:00
2009-10-31 00:00:00
2009-11-30 00:00:00
2009-12-31 00:00:00
2010-01-31 00:00:00
2010-02-28 00:00:00
2010-03-31 00:00:00
2010-04-30 00:00:00
2010-05-31 00:00:00
2010-06-30 00:00:00
2010-07-31 00:00:00
2010-08-31 00:00:00
2010-09-30 00:00:00
2010-10-31 00:00:00
2010-11-30 00:00:00
2010-12-31 00:00:00
2011-01-31 00:00:00
2011-02-28 00:00:00
2011-03-31 00:00:00
2011-04-30 00:00:00
2011-05-31 00:00:00
2011-06-30 00:00:00
2011-07-31 00:00:00
2011-08-31 00:00:00
2011-09-30 00:00:00
2011-10-31 00:00:00
2011-11-30 00:00:00
2011-12-31 00:00:00
2012-01-31 00:00:00
2012-02-29 00:00:00
2012-03-31 00:00:00
2012-04-30 00:00:00
2012-05-31 00:00:00
2012-06-30 00:00:00
2012-07-31 00:00:00
2012-08-31 00:00:00
2012-09-30 00:00:00
2012-10-31 00:00:00
2012-11-30 00:00:00
2012-12-31 00:00:00
2013-01-31 00:00:00
2013-02-28 00:00:00
2013-03-31 00:00:00
2013-04-30 00:00:00
2013-05-31 00:00:00
2013-06-30 00:00:00
2013-07-31 00:00:00
2013-08-31 00:00:00
2013-09-30 00:00:00
2013-10-31 00:00:00
2013-11-30 00:00:00
2013-12-31 00:00:00
2014-01-31 00:00:00
2014-02-28 00:00:00
2014-03-31 00:00:00
2014-04-30 00:00:00
2014-05-31 00:00:00
2014-06-30 00:00:00
2014-07-31 00:00:00
2014-08-31 00:00:00
2014-09-30 00:00:00
2014-10-31 00:00:00
2014-11-30 00:00:00
2014-12-31 00:00:00
2015-01-31 00:00:00
2015-02-28 00:00:00
2015-03-31 00:00:00
2015-04-30 00:00:00
2015-05-31 00:00:00
2015-06-30 00:00:00
2015-07-31 00:00:00
2015-08-31 00:00:00
2015-09-30 00:00:00
2015-10-31 00:00:00
2015-11-30 00:00:00
2015-12-31 00:00:00
2016-01-31 00:00:00
2016-02-29 00:00:00
2016-03-31 00:00:00
2016-04-30 00:00:00
2016-05-31 00:00:00
2016-06-30 00:00:00
2016-07-31 00:00:00
2016-08-31 00:00:00
2016-09-30 00:00:00
2016-10-31 00:00:00
2016-11-30 00:00:00
2016-12-31 00:00:00
2017-01-31 00:00:00
2017-02-28 00:00:00
2017-03-31 00:00:00
2017-04-30 00:00:00
2017-05-31 00:00:00
2017-06-30 00:00:00
2017-07-31 00:00:00
2017-08-31 00:00:00
2017-09-30 00:00:00
2017-10-31 00:00:00
2017-11-30 00:00:00
2017-12-31 00:00:00
2018-01-31 00:00:00
2018-02-28 00:00:00
2018-03-31 00:00:00
2018-04-30 00:00:00
2018-05-31 00:00:00
2018-06-30 00:00:00
2018-07-31 00:00:00
2018-08-31 00:00:00
2018-09-30 00:00:00
2018-10-31 00:00:00
2018-11-30 00:00:00
2018-12-31 00:00:00
2019-01-31 00:00:00
2019-02-28 00:00:00
2019-03-31 00:00:00
2019-04-30 00:00:00
2019-05-31 00:00:00
2019-06-30 00:00:00
2019-07-31 00:00:00
2019-08-31 00:00:00
2019-09-30 00:00:00
2019-10-31 00:00:00
2019-11-30 00:00:00
2019-12-31 00:00:00
2020-01-31 00:00:00
2020-02-29 00:00:00
2020-03-31 00:00:00
2020-04-30 00:00:00
2020-05-31 00:00:00
2020-06-30 00:00:00
2020-07-31 00:00:00
2020-08-31 00:00:00
2020-09-30 00:00:00
2020-10-31 00:00:00
2020-11-30 00:00:00
2020-12-31 00:00:00
2021-01-31 00:00:00

In [19]:
idiovol

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-30,0.042336,0.043182,NaN,0.069319,0.027019,0.042817,0.073031,0.042431,0.048318,0.058866,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-31,0.043564,0.042815,NaN,0.069378,0.026797,0.043452,0.07188,0.042083,0.048154,0.055027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-30,0.041337,0.041476,NaN,0.069393,0.026237,0.042937,0.071142,0.041901,0.048477,0.054682,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-31,0.041092,0.040883,NaN,0.070162,0.026263,0.042644,0.071593,0.041789,0.04925,0.054627,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-31,0.040948,0.039867,NaN,0.070409,0.026427,0.042274,0.080975,0.041637,0.048971,0.052928,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
idiovol.to_csv('../../Data/factors/idiovol.csv')

# ear
Sum of daily returns in three days around earnings announcement.  
财报公布日附近三天的日回报率之和  
该因子如何与其他因子在日期上对齐？

In [24]:
dret = mm.extract_variable(path='../../Data/raw_data/01日个股回报率',
                           fileType='csv',
                           variable='Dretwd',
                           time_col='Trddt',
                           code_col='Stkcd',
                           print_fileName=True
                      )
dret

../../Data/raw_data/01日个股回报率\TRD_Dalyr00.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr01.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr02.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr03.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr04.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr05.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr06.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr07.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr08.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr09.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr10.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr11.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr12.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr13.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr14.csv
../../Data/raw_data/01日个股回报率\TRD_Dalyr15.csv

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trddt,,,,,,,,,,,,,,,,,,,,,
1999-12-01,0.007110,-0.001800,-0.004847,0.002445,0.002805,0.005797,0.012107,0.023650,0.005128,0.003315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-02,-0.008573,-0.023445,0.000000,0.007317,-0.027972,-0.013449,-0.020335,-0.008287,-0.010204,0.007709,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-03,-0.009156,0.018467,0.008117,0.037530,-0.007194,-0.006816,-0.003663,0.007597,0.002577,-0.010929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-06,-0.021047,0.012693,0.030596,0.037340,-0.002899,0.003922,-0.014706,0.009550,0.000000,-0.003315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-07,-0.003671,-0.006267,-0.017188,-0.021372,-0.005814,0.006836,0.004975,0.002987,0.007712,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-17,-0.006736,0.008213,NaN,0.036849,0.008696,0.015766,0.027523,-0.003623,0.006930,0.005208,...,0.033722,0.018334,0.008105,0.040665,0.026592,0.017510,0.035824,0.100028,0.016844,-0.000720
2022-01-18,0.018496,0.034499,NaN,0.020435,-0.051724,0.000000,0.031250,0.003636,0.015829,-0.028497,...,-0.006587,-0.013117,-0.020771,-0.100000,-0.035446,0.001912,-0.025198,-0.038314,-0.037548,-0.047550
2022-01-19,-0.001211,0.014358,NaN,-0.037875,-0.031818,0.008869,-0.050505,0.036232,-0.027778,0.008000,...,-0.055573,-0.008861,0.003421,-0.046218,0.037456,-0.021628,0.007603,-0.054449,0.020080,0.026475
2022-01-20,0.050303,0.009589,NaN,-0.034389,-0.018779,-0.004396,0.030395,-0.041958,-0.024390,-0.021164,...,0.099967,-0.040231,-0.021480,0.014684,-0.057221,-0.032510,-0.044517,0.022472,-0.077615,-0.030951
2022-01-21,0.001154,-0.021257,NaN,-0.010309,0.009569,-0.004415,0.008850,-0.036496,0.005000,-0.005405,...,-0.082067,0.008219,-0.020209,-0.084419,-0.073699,-0.022177,-0.010266,-0.021978,-0.031707,0.000000

In [25]:
df = pd.read_csv('../../Data/raw_data/18年、中、季报基本情况/IAR_Rept.csv')
df

,Stkcd,Stknme,Sctcd,Reptyp,Accper,Annodt,Annowk,Annopub,Profita,Profitb,Asseta,Assetb,Erana,Eranb
0,1,深发展A,2,4,1990-12-31,1991-04-30,2,1,NaN,NaN,2.627,NaN,NaN,NaN
1,1,深发展A,2,4,1991-12-31,1992-04-30,4,1,1.126500e+08,NaN,6.406,NaN,NaN,NaN
2,1,深发展A,2,2,1992-06-30,1992-07-28,2,1,9.890000e+07,NaN,NaN,NaN,NaN,NaN
3,1,深发展A,2,4,1992-12-31,1993-02-26,5,1,1.924300e+08,NaN,5.150,NaN,1.39000,NaN
4,1,深发展A,2,2,1993-06-30,1993-08-05,4,1,1.374663e+08,NaN,NaN,NaN,0.55165,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206805,900957,凌云B股,1,3,2020-09-30,2020-10-29,4,2,1.678628e+07,16036418.10,NaN,NaN,0.04810,0.0459
206806,900957,凌云B股,1,4,2020-12-31,2021-04-09,5,2,2.180890e+07,20799256.12,NaN,NaN,0.06250,0.0596
206807,900957,凌云B股,1,1,2021-03-31,2021-04-27,2,2,8.359113e+06,8359112.84,NaN,NaN,0.02400,0.0240
206808,900957,凌云B股,1,2,2021-06-30,2021-08-12,4,2,1.490982e+07,14909818.13,NaN,NaN,0.04270,0.0427
206809,900957,凌云B股,1,3,2021-09-30,2021-10-29,5,2,2.097336e+07,20973364.91,NaN,NaN,0.06010,0.0601

In [26]:
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<= 609999))]
df

,Stkcd,Stknme,Sctcd,Reptyp,Accper,Annodt,Annowk,Annopub,Profita,Profitb,Asseta,Assetb,Erana,Eranb
0,1,深发展A,2,4,1990-12-31,1991-04-30,2,1,NaN,NaN,2.627,NaN,NaN,NaN
1,1,深发展A,2,4,1991-12-31,1992-04-30,4,1,1.126500e+08,NaN,6.406,NaN,NaN,NaN
2,1,深发展A,2,2,1992-06-30,1992-07-28,2,1,9.890000e+07,NaN,NaN,NaN,NaN,NaN
3,1,深发展A,2,4,1992-12-31,1993-02-26,5,1,1.924300e+08,NaN,5.150,NaN,1.39000,NaN
4,1,深发展A,2,2,1993-06-30,1993-08-05,4,1,1.374663e+08,NaN,NaN,NaN,0.55165,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200258,605580,恒盛能源,1,3,2021-09-30,2021-10-30,6,2,8.991872e+07,8.524728e+07,NaN,NaN,0.58000,0.4262
200259,605588,冠石科技,1,3,2021-09-30,2021-10-26,2,2,6.719253e+07,6.153544e+07,NaN,NaN,1.18000,0.8418
200260,605589,圣泉集团,1,3,2021-09-30,2021-10-26,2,2,5.260509e+08,4.471929e+08,NaN,NaN,0.75000,0.5772
200261,605598,上海港湾,1,3,2021-09-30,2021-10-30,6,2,6.696321e+07,6.595164e+07,NaN,NaN,0.52000,0.3818
200262,605599,菜百股份,1,3,2021-09-30,2021-10-28,4,2,2.659621e+08,2.658805e+08,NaN,NaN,0.38000,0.3418

In [27]:
df['Annodt'] = pd.to_datetime(df['Annodt'], format='%Y-%m-%d')

In [28]:
stk_annodt = df[['Stkcd','Annodt']]
stk_annodt

         Stkcd     Annodt
0            1 1991-04-30
1            1 1992-04-30
2            1 1992-07-28
3            1 1993-02-26
4            1 1993-08-05
...        ...        ...
200258  605580 2021-10-30
200259  605588 2021-10-26
200260  605589 2021-10-26
200261  605598 2021-10-30
200262  605599 2021-10-28

[170503 rows x 2 columns]

In [29]:
stk_annodt = stk_annodt.sort_values(by='Annodt')
stk_annodt

         Stkcd     Annodt
153550  600602 1990-12-31
158460  600656 1990-12-31
158360  600655 1990-12-31
158260  600654 1990-12-31
158160  600653 1990-12-31
...        ...        ...
48782     2092 2022-02-17
192318  603169 2022-02-19
82576     2947 2022-02-22
65098     2402 2022-02-22
79291     2759 2022-02-22

[170503 rows x 2 columns]

In [30]:
dret_s3d = dret.rolling(window=3, center=True).sum()
dret_s3d

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trddt,,,,,,,,,,,,,,,,,,,,,
1999-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-02,-0.010619,-0.006778,0.003270,0.047292,-0.032361,-0.014468,-0.011891,0.022960,-0.002499,0.000095,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-03,-0.038776,0.007715,0.038713,0.082187,-0.038065,-0.016343,-0.038704,0.008860,-0.007627,-0.006535,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-06,-0.033874,0.024893,0.021525,0.053498,-0.015907,0.003942,-0.013394,0.020134,0.010289,-0.014244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-07,-0.024718,-0.023304,-0.005670,-0.000124,-0.008713,-0.002821,-0.009731,0.007077,-0.007594,-0.015510,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-17,-0.026520,0.004161,NaN,0.062842,-0.068452,-0.010550,0.055724,0.018463,0.058653,-0.041192,...,0.066569,-0.021548,-0.037048,-0.069292,-0.049794,0.004096,-0.011641,0.128561,-0.071849,-0.079651
2022-01-18,0.010549,0.057070,NaN,0.019409,-0.074846,0.024635,0.008268,0.036245,-0.005019,-0.015289,...,-0.028438,-0.003644,-0.009245,-0.105553,0.028602,-0.002206,0.018229,0.007265,-0.000624,-0.021795
2022-01-19,0.067588,0.058446,NaN,-0.051829,-0.102321,0.004473,0.011140,-0.002090,-0.036339,-0.041661,...,0.037807,-0.062209,-0.038830,-0.131534,-0.055211,-0.052226,-0.062112,-0.070291,-0.095083,-0.052026
2022-01-20,0.050246,0.002690,NaN,-0.082573,-0.041028,0.000058,-0.011260,-0.042222,-0.047168,-0.018569,...,-0.037673,-0.040873,-0.038268,-0.115953,-0.093464,-0.076315,-0.047180,-0.053955,-0.089242,-0.004476
2022-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
ear = pd.DataFrame(columns=dret_s3d.columns, index=pd.date_range(start='1990-01-01', end='2022-02-28'))
for i in range(len(stk_annodt)):
    stk = stk_annodt.iloc[i,0]
    adt = stk_annodt.iloc[i,1]
    if stk in dret_s3d.columns:
        if adt in dret_s3d.index:  # 如果公布日是交易日
            ear.loc[adt, stk] = dret_s3d.loc[adt, stk]
        else:  # 如果公布日不是交易日
            afterdates = dret_s3d.loc[adt:, stk]
            if not afterdates.empty:
                ear.loc[adt, stk] = afterdates[0]

In [33]:
ear

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
1990-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
ear.to_csv('../../Data/factors/ear.csv')

# volatility
Standard deviation of daily returns in a month

In [35]:
dret = mm.extract_variable(path='../../Data/raw_data/01日个股回报率',
                          fileType='csv',
                          variable='Dretwd',
                          time_col='Trddt',
                          code_col='Stkcd')
dret

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trddt,,,,,,,,,,,,,,,,,,,,,
1999-12-01,0.007110,-0.001800,-0.004847,0.002445,0.002805,0.005797,0.012107,0.023650,0.005128,0.003315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-02,-0.008573,-0.023445,0.000000,0.007317,-0.027972,-0.013449,-0.020335,-0.008287,-0.010204,0.007709,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-03,-0.009156,0.018467,0.008117,0.037530,-0.007194,-0.006816,-0.003663,0.007597,0.002577,-0.010929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-06,-0.021047,0.012693,0.030596,0.037340,-0.002899,0.003922,-0.014706,0.009550,0.000000,-0.003315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-07,-0.003671,-0.006267,-0.017188,-0.021372,-0.005814,0.006836,0.004975,0.002987,0.007712,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-17,-0.006736,0.008213,NaN,0.036849,0.008696,0.015766,0.027523,-0.003623,0.006930,0.005208,...,0.033722,0.018334,0.008105,0.040665,0.026592,0.017510,0.035824,0.100028,0.016844,-0.000720
2022-01-18,0.018496,0.034499,NaN,0.020435,-0.051724,0.000000,0.031250,0.003636,0.015829,-0.028497,...,-0.006587,-0.013117,-0.020771,-0.100000,-0.035446,0.001912,-0.025198,-0.038314,-0.037548,-0.047550
2022-01-19,-0.001211,0.014358,NaN,-0.037875,-0.031818,0.008869,-0.050505,0.036232,-0.027778,0.008000,...,-0.055573,-0.008861,0.003421,-0.046218,0.037456,-0.021628,0.007603,-0.054449,0.020080,0.026475
2022-01-20,0.050303,0.009589,NaN,-0.034389,-0.018779,-0.004396,0.030395,-0.041958,-0.024390,-0.021164,...,0.099967,-0.040231,-0.021480,0.014684,-0.057221,-0.032510,-0.044517,0.022472,-0.077615,-0.030951
2022-01-21,0.001154,-0.021257,NaN,-0.010309,0.009569,-0.004415,0.008850,-0.036496,0.005000,-0.005405,...,-0.082067,0.008219,-0.020209,-0.084419,-0.073699,-0.022177,-0.010266,-0.021978,-0.031707,0.000000

In [36]:
volatility = dret.resample('M').apply(np.std)
volatility

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trddt,,,,,,,,,,,,,,,,,,,,,
1999-12-31,0.016294,0.027807,0.025421,0.023333,0.017019,0.014571,0.022512,0.020137,0.019272,0.021604,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-31,0.028339,0.042418,0.034445,0.031346,0.041065,0.037841,0.036178,0.029278,0.024398,0.029614,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-02-29,0.038460,0.057716,0.061224,0.043163,0.047003,0.052453,0.062822,0.068395,0.041792,0.051140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-03-31,0.025564,0.037218,0.046805,0.035553,0.035795,0.029800,0.060247,0.028404,0.029618,0.047775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-04-30,0.012733,0.027489,0.028677,0.023574,0.034587,0.028044,0.027051,0.023011,0.039441,0.030086,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-30,0.029402,0.030689,NaN,0.031690,0.022525,0.016550,0.031877,0.021234,0.059050,0.012497,...,0.012930,NaN,NaN,NaN,0.057427,0.057179,0.029140,0.050794,0.181807,0.131818
2021-10-31,0.020842,0.028587,NaN,0.028693,0.021114,0.014924,0.028988,0.021032,0.050706,0.034009,...,0.013789,0.136364,0.147920,0.136620,0.047870,0.053565,0.040058,0.033055,0.021283,0.024638
2021-11-30,0.019814,0.031337,NaN,0.027923,0.017086,0.011932,0.036364,0.008780,0.039396,0.016186,...,0.017622,0.054732,0.025485,0.023502,0.030949,0.030055,0.023322,0.032380,0.015576,0.013381
2021-12-31,0.014105,0.017994,NaN,0.019807,0.016630,0.021492,0.026381,0.050295,0.022185,0.015188,...,0.012236,0.030968,0.022886,0.040810,0.058252,0.014734,0.019439,0.034025,0.037007,0.020210
2022-01-31,0.021310,0.024515,NaN,0.036269,0.025114,0.011277,0.031623,0.028540,0.025039,0.015446,...,0.051138,0.030366,0.017202,0.071683,0.038580,0.016354,0.022121,0.042608,0.056896,0.042606

In [37]:
volatility.to_csv('../../Data/factors/volatility.csv')

# roavol
 Standard deviation of 16 quarters of income before extraordinary items divided by
average total assets.

In [55]:
# B001100000 [营业总收入] - 企业经营过程中所有收入之和.
df = pd.read_csv('../../Data/raw_data/14利润表/FS_Comins.csv')
df = df[df['Typrep'] == 'A' ]
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.to_datetime(df['Accper'], format='%Y-%m-%d')
df

,Stkcd,Accper,Typrep,B001100000,B001101000,Bbd1102000,Bbd1102101,Bbd1102203,B0i1103000,B0i1103101,...,B006000102,B001216000,B001211101,B001211203,B001305000,B001302201,B001306000,B001307000,B001308000,B002000301
0,1,1991-12-31,A,3.346900e+08,3.346900e+08,0.000000e+00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1992-12-31,A,4.755108e+08,4.755108e+08,0.000000e+00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1993-06-30,A,2.664955e+08,2.664955e+08,0.000000e+00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1993-12-31,A,4.078706e+08,NaN,3.617215e+08,7.589449e+08,3.972235e+08,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1994-06-30,A,2.970876e+08,NaN,2.787976e+08,4.612229e+08,1.824254e+08,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465487,605580,2021-09-30,A,5.079318e+08,5.079318e+08,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5062385.63,885668.07,7995011.61,NaN,NaN,-3981857.63,1072595.37,NaN
465488,605588,2021-09-30,A,1.081463e+09,1.081463e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,2.266605e+07,4106938.44,654500.08,5054719.67,NaN,NaN,-2500217.31,-15645.79,NaN
465489,605589,2021-09-30,A,6.361000e+09,6.361000e+09,NaN,NaN,NaN,NaN,NaN,...,13175991.09,2.901087e+08,97226241.14,14141176.95,71395803.16,NaN,NaN,37376711.88,673168.38,NaN
465490,605598,2021-09-30,A,5.882567e+08,5.882567e+08,NaN,NaN,NaN,NaN,NaN,...,NaN,7.708755e+06,2890938.40,2591451.61,852154.24,NaN,NaN,22378421.40,-35719.53,NaN
465491,605599,2021-09-30,A,7.259858e+09,7.259858e+09,NaN,NaN,NaN,NaN,NaN,...,-894268.75,3.252396e+06,15083402.02,2418018.01,3372994.74,NaN,NaN,-14559633.18,37149.36,NaN

In [56]:
income = df.pivot_table(values='B001100000', index='Accper', columns='Stkcd')
#income = income.fillna(method='ffill')
income

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,3.346900e+08,NaN,4.686506e+08,4.987143e+07,NaN,NaN,NaN,NaN,4.090975e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,4.755108e+08,6.613562e+08,7.877559e+08,9.480596e+07,3.786469e+07,1.081658e+08,1.397244e+08,1.403785e+07,7.733561e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,2.664955e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,4.078706e+08,1.084045e+09,1.054117e+09,2.117347e+08,3.406867e+07,1.510638e+08,1.729648e+08,1.457602e+07,9.806126e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,3.827100e+10,6.226410e+10,NaN,3.653115e+07,4.816156e+07,9.182869e+08,1.315511e+07,1.492886e+08,3.715024e+09,2.280631e+08,...,5.536006e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,7.683500e+10,1.671109e+11,NaN,9.301226e+07,1.636117e+08,1.473671e+09,5.495203e+07,5.279869e+08,8.048322e+09,5.629963e+08,...,1.341035e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,1.151080e+11,2.714858e+11,NaN,1.662119e+08,2.919397e+08,2.302271e+09,1.278467e+08,1.042818e+09,1.220675e+10,1.056525e+09,...,2.111076e+09,3.213201e+09,2.225451e+09,1.560928e+09,1.405946e+09,5.079318e+08,1.081463e+09,6.361000e+09,5.882567e+08,7.259858e+09
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
# A001000000 [资产总计] - 资产各项目之总计.
df = pd.read_csv('../../Data/raw_data/16资产负债表/FS_Combas.csv')
df = df[df['Typrep'] == 'A' ]
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<=609999))]
df['Accper'] = pd.to_datetime(df['Accper'], format='%Y-%m-%d')
df

,Stkcd,Accper,Typrep,A001101000,A0d1101101,A0d1102000,A0d1102101,A0b1103000,A0b1104000,A0b1105000,...,A003200000,A003000000,A004000000,A001127000,A001128000,A001226000,A001227000,A001228000,A001229000,A002128000
0,1,1990-12-31,A,8.042000e+08,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,2.365100e+08,2.919190e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1991-12-31,A,3.310000e+07,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,5.779600e+08,4.354460e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1992-12-31,A,6.320410e+07,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,5.456622e+08,7.522847e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1993-12-31,A,0.000000e+00,NaN,0.0,NaN,NaN,90814922.4,NaN,...,NaN,1.189130e+09,9.337871e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1994-06-30,A,0.000000e+00,NaN,0.0,NaN,1.853747e+09,NaN,NaN,...,NaN,1.512913e+09,1.246595e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463819,605580,2021-09-30,A,1.782109e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.125735e+08,9.314849e+08,1.260467e+07,NaN,NaN,NaN,NaN,NaN,1.872911e+06
463820,605588,2021-09-30,A,5.131789e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.003418e+08,1.288794e+09,4.095044e+06,NaN,NaN,NaN,4000000.00,NaN,2.522840e+05
463821,605589,2021-09-30,A,1.386646e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,1.526975e+08,7.930826e+09,1.310657e+10,1.285200e+09,NaN,NaN,NaN,47955396.42,NaN,6.909770e+07
463822,605598,2021-09-30,A,8.450433e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.438024e+09,1.776012e+09,5.000000e+05,2.850373e+08,NaN,NaN,NaN,NaN,3.441598e+07
463823,605599,2021-09-30,A,1.255342e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,1.078357e+07,3.110357e+09,4.803754e+09,NaN,NaN,NaN,NaN,NaN,NaN,3.417211e+08

In [58]:
assets = df.pivot_table(values='A001000000', index='Accper', columns='Stkcd')
assets

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,2.919190e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,4.354460e+09,5.684941e+08,6.078172e+08,1.340786e+08,NaN,NaN,NaN,NaN,6.642928e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,7.522847e+09,9.455016e+08,1.018333e+09,3.224412e+08,6.138121e+08,2.288015e+08,1.322528e+08,1.082672e+08,1.546114e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,9.337871e+09,2.136159e+09,1.921612e+09,7.718936e+08,6.920086e+08,5.557977e+08,3.135394e+08,2.408760e+08,3.270337e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,4.572974e+12,1.907860e+12,NaN,1.579540e+09,2.404022e+09,1.605208e+10,3.789513e+08,1.317685e+10,3.223258e+10,3.558606e+09,...,2.400768e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,4.723520e+12,1.955046e+12,NaN,1.556155e+09,2.426484e+09,1.876161e+10,4.098859e+08,1.274585e+10,3.305083e+10,3.731692e+09,...,2.523014e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,4.853074e+12,1.967403e+12,NaN,1.623624e+09,2.485983e+09,1.981674e+10,4.286182e+08,1.317730e+10,3.436544e+10,4.039276e+09,...,2.588452e+09,7.710989e+09,2.392599e+09,1.672137e+09,4.828118e+09,9.314849e+08,1.288794e+09,1.310657e+10,1.776012e+09,4.803754e+09
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
aver_assets = assets.rolling(f'{16*3*30}D').mean()
aver_assets

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,2.919190e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,3.636825e+09,5.684941e+08,6.078172e+08,1.340786e+08,NaN,NaN,NaN,NaN,6.642928e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,4.932166e+09,7.569979e+08,8.130754e+08,2.282599e+08,6.138121e+08,2.288015e+08,1.322528e+08,1.082672e+08,1.105204e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,4.932166e+09,7.569979e+08,8.130754e+08,2.282599e+08,6.138121e+08,2.288015e+08,1.322528e+08,1.082672e+08,1.105204e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,6.033592e+09,1.216718e+09,1.182588e+09,4.094711e+08,6.529104e+08,3.922996e+08,2.228961e+08,1.745716e+08,1.826915e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,3.603216e+12,1.456861e+12,NaN,6.524952e+08,2.898297e+09,1.401290e+10,4.563011e+08,1.064766e+10,2.874155e+10,3.717057e+09,...,1.992528e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,3.685678e+12,1.510604e+12,NaN,7.238498e+08,2.887387e+09,1.415956e+10,4.507043e+08,1.092106e+10,2.924651e+10,3.703366e+09,...,2.128608e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,3.771540e+12,1.564592e+12,NaN,7.937165e+08,2.869218e+09,1.446217e+10,4.487920e+08,1.115008e+10,2.970975e+10,3.694508e+09,...,2.227209e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,3.861834e+12,1.614541e+12,NaN,8.664751e+08,2.853066e+09,1.480922e+10,4.486444e+08,1.134509e+10,3.011731e+10,3.691813e+09,...,2.299458e+09,7.710989e+09,2.392599e+09,1.672137e+09,4.828118e+09,9.314849e+08,1.288794e+09,1.310657e+10,1.776012e+09,4.803754e+09
2021-12-31,3.933994e+12,1.667387e+12,NaN,9.367847e+08,2.846121e+09,1.500561e+10,4.493466e+08,1.142354e+10,3.047118e+10,3.760832e+09,...,2.299458e+09,7.710989e+09,2.392599e+09,1.672137e+09,4.828118e+09,9.314849e+08,1.288794e+09,1.310657e+10,1.776012e+09,4.803754e+09

In [60]:
roavol = income.rolling(window=f'{16*3*30}D',min_periods=2).std() / aver_assets  # std([x1/yn,...,xn/yn]) = std([x1,...,xn]) / yn
roavol

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605500,605507,605555,605567,605577,605580,605588,605589,605598,605599
Accper,,,,,,,,,,,,,,,,,,,,,
1990-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,0.020189,NaN,0.277516,0.139199,NaN,NaN,NaN,NaN,0.233052,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-06-30,0.021611,NaN,0.277516,0.139199,NaN,NaN,NaN,NaN,0.233052,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,0.014984,0.245649,0.247871,0.204062,0.004111,0.077322,0.105450,0.002180,0.158370,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-01,0.010088,0.084821,NaN,0.161777,0.063617,0.074317,0.027841,0.098366,0.130917,0.154292,...,0.050638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-31,0.009634,0.079826,NaN,0.143639,0.064527,0.074368,0.027942,0.096216,0.123497,0.153356,...,0.425429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-30,0.009246,0.074864,NaN,0.127453,0.065563,0.073146,0.030675,0.094401,0.118109,0.151990,...,0.336882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,0.009225,0.072241,NaN,0.115037,0.066004,0.071407,0.058382,0.092666,0.121884,0.154170,...,0.304178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-31,0.009412,0.073709,NaN,0.112777,0.065183,0.069863,0.061742,0.092623,0.127741,0.160297,...,0.304178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
roavol.to_csv('../../Data/factors/roavol.csv')