In [10]:
import my_methods as mm
import pandas as pd
import numpy as np
import datetime as dt

In [11]:
df = pd.read_csv('../../Data/raw_data/02æœˆä¸ªè‚¡å›žæŠ¥çŽ‡/TRD_Mnth.csv')
df = df[df['Stkcd'].map(lambda x: (0<=x and x<=9999) or (600000<=x and x<= 609999))]
df['Trdmnt'] = pd.DatetimeIndex(df['Trdmnt']).to_period(freq='M').to_timestamp(freq='M')
df

,Stkcd,Trdmnt,Opndt,Mopnprc,Clsdt,Mclsprc,Mnshrtrd,Mnvaltrd,Msmvosd,Msmvttl,Ndaytrd,Mretwd,Mretnd,Markettype,Capchgdt,Ahshrtrd_M,Ahvaltrd_M
0,1,1991-04-30,3,49.00,30,43.68,13400,6.150000e+05,1157520.00,2118487.47,20,NaN,NaN,4,1991-04-03,NaN,NaN
1,1,1991-05-31,2,43.46,31,38.34,187800,7.675000e+06,1016010.00,1859496.56,24,-0.122253,0.235714,4,1991-04-03,NaN,NaN
2,1,1991-06-30,1,38.53,28,33.99,30600,1.094000e+06,900735.00,1648520.81,23,-0.113459,-0.113459,4,1991-04-03,NaN,NaN
3,1,1991-07-31,1,33.65,31,29.54,6100,1.940430e+05,782810.00,1432695.05,16,-0.130921,-0.130921,4,1991-04-03,NaN,NaN
4,1,1991-08-31,1,29.39,31,15.00,3243100,4.957624e+07,674833.82,1346274.65,15,-0.411588,-0.411587,4,1991-08-01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625727,605598,2021-12-31,1,14.72,31,15.93,154907350,2.558677e+09,688071.93,2751803.43,23,0.086630,0.086630,1,2021-09-17,0.0,0.0
625728,605599,2021-09-30,9,12.00,30,12.69,157545260,2.346894e+09,987000.28,9870000.28,14,NaN,NaN,1,2021-09-09,0.0,0.0
625729,605599,2021-10-31,8,12.74,29,11.67,75453839,9.781484e+08,907666.93,9076666.93,16,-0.080378,-0.080378,1,2021-09-09,0.0,0.0
625730,605599,2021-11-30,1,11.67,30,12.39,71873065,8.717006e+08,963666.94,9636666.94,22,0.061697,0.061697,1,2021-09-09,0.0,0.0
625731,605599,2021-12-31,1,12.34,31,13.46,126367554,1.634912e+09,1046889.19,10468889.19,23,0.086360,0.086360,1,2021-09-09,0.0,0.0

In [12]:
monthly_return = df.pivot_table(values='Mretwd', index='Trdmnt', columns='Stkcd')
monthly_return

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdmnt,,,,,,,,,,,,,,,,,,,,,
1991-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,0.039972,NaN,-0.042568,-0.029869,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,NaN,-0.126574,NaN,-0.126323,-0.126363,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,NaN,-0.116085,NaN,-0.096931,-0.116740,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-05-31,-0.122253,-0.030901,NaN,-0.114490,-0.123026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,0.006218,0.014775,NaN,-0.124602,0.143541,0.024887,-0.057339,0.093137,0.321460,-0.025907,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,0.007303,0.076263,NaN,-0.014026,-0.117155,-0.008830,0.029197,0.008969,-0.315245,-0.021277,...,-0.060453,NaN,NaN,NaN,-0.150468,-0.043646,-0.175308,-0.112635,NaN,NaN
2021-10-31,0.087563,-0.145472,NaN,-0.115385,0.037915,-0.071269,0.035461,-0.031111,0.090198,0.070652,...,-0.063983,NaN,NaN,NaN,0.025424,0.069324,-0.087818,-0.001672,-0.093937,-0.080378
2021-11-30,-0.105641,0.002746,NaN,0.120905,0.000000,-0.016787,0.344749,-0.004587,-0.152080,-0.022843,...,0.108493,0.425094,0.019601,0.006061,0.053719,-0.059427,0.180477,0.319156,0.077941,0.061697
2021-12-31,-0.055046,0.082147,NaN,0.031881,0.050228,0.087805,0.033956,0.354839,-0.186125,-0.020779,...,0.016573,-0.106439,0.017236,0.425703,0.150588,-0.067777,-0.104725,-0.027672,0.086630,0.086360

In [13]:
future_1_monthly_return = monthly_return.shift(-1).dropna(how='all')
future_1_monthly_return

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trdmnt,,,,,,,,,,,,,,,,,,,,,
1991-01-31,NaN,0.039972,NaN,-0.042568,-0.029869,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,NaN,-0.126574,NaN,-0.126323,-0.126363,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,NaN,-0.116085,NaN,-0.096931,-0.116740,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,-0.122253,-0.030901,NaN,-0.114490,-0.123026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-05-31,-0.113459,-0.303809,NaN,-0.454545,-0.109005,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-31,0.006218,0.014775,NaN,-0.124602,0.143541,0.024887,-0.057339,0.093137,0.321460,-0.025907,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-08-31,0.007303,0.076263,NaN,-0.014026,-0.117155,-0.008830,0.029197,0.008969,-0.315245,-0.021277,...,-0.060453,NaN,NaN,NaN,-0.150468,-0.043646,-0.175308,-0.112635,NaN,NaN
2021-09-30,0.087563,-0.145472,NaN,-0.115385,0.037915,-0.071269,0.035461,-0.031111,0.090198,0.070652,...,-0.063983,NaN,NaN,NaN,0.025424,0.069324,-0.087818,-0.001672,-0.093937,-0.080378
2021-10-31,-0.105641,0.002746,NaN,0.120905,0.000000,-0.016787,0.344749,-0.004587,-0.152080,-0.022843,...,0.108493,0.425094,0.019601,0.006061,0.053719,-0.059427,0.180477,0.319156,0.077941,0.061697
2021-11-30,-0.055046,0.082147,NaN,0.031881,0.050228,0.087805,0.033956,0.354839,-0.186125,-0.020779,...,0.016573,-0.106439,0.017236,0.425703,0.150588,-0.067777,-0.104725,-0.027672,0.086630,0.086360

In [9]:
future_1_monthly_return.to_csv('../../Data/future_1_monthly_return.csv')