In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
import my_methods as mm
from sklearn.preprocessing import PolynomialFeatures

In [12]:
data = mm.extract_variable(path='C:/Users/ShaunMarx/助研_人大/project01_China_stock/Data/raw_data/01日个股回报率',
                   variable='Dretwd',
                   time_col='Trddt',
                   code_col='Stkcd')
data

Stkcd,1,2,3,4,5,6,7,8,9,10,...,605507,605555,605566,605567,605577,605580,605588,605589,605598,605599
Trddt,,,,,,,,,,,,,,,,,,,,,
1999-12-01,0.007110,-0.001800,-0.004847,0.002445,0.002805,0.005797,0.012107,0.023650,0.005128,0.003315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-02,-0.008573,-0.023445,0.000000,0.007317,-0.027972,-0.013449,-0.020335,-0.008287,-0.010204,0.007709,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-03,-0.009156,0.018467,0.008117,0.037530,-0.007194,-0.006816,-0.003663,0.007597,0.002577,-0.010929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-06,-0.021047,0.012693,0.030596,0.037340,-0.002899,0.003922,-0.014706,0.009550,0.000000,-0.003315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-07,-0.003671,-0.006267,-0.017188,-0.021372,-0.005814,0.006836,0.004975,0.002987,0.007712,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-17,-0.006736,0.008213,NaN,0.036849,0.008696,0.015766,0.027523,-0.003623,0.006930,0.005208,...,0.033722,0.018334,0.008105,0.040665,0.026592,0.017510,0.035824,0.100028,0.016844,-0.000720
2022-01-18,0.018496,0.034499,NaN,0.020435,-0.051724,0.000000,0.031250,0.003636,0.015829,-0.028497,...,-0.006587,-0.013117,-0.020771,-0.100000,-0.035446,0.001912,-0.025198,-0.038314,-0.037548,-0.047550
2022-01-19,-0.001211,0.014358,NaN,-0.037875,-0.031818,0.008869,-0.050505,0.036232,-0.027778,0.008000,...,-0.055573,-0.008861,0.003421,-0.046218,0.037456,-0.021628,0.007603,-0.054449,0.020080,0.026475
2022-01-20,0.050303,0.009589,NaN,-0.034389,-0.018779,-0.004396,0.030395,-0.041958,-0.024390,-0.021164,...,0.099967,-0.040231,-0.021480,0.014684,-0.057221,-0.032510,-0.044517,0.022472,-0.077615,-0.030951
2022-01-21,0.001154,-0.021257,NaN,-0.010309,0.009569,-0.004415,0.008850,-0.036496,0.005000,-0.005405,...,-0.082067,0.008219,-0.020209,-0.084419,-0.073699,-0.022177,-0.010266,-0.021978,-0.031707,0.000000

In [32]:
window = 10
data_std = data.rolling(window=window, closed='left').apply(np.std)
data_std

KeyboardInterrupt:

In [ ]:
data_select = data_std.applymap(lambda x: x<0.02)

In [ ]:
data1 =data.mask(data_select)
data1

In [13]:
target=data1.T
target

Trddt,1999-12-01,1999-12-02,1999-12-03,1999-12-06,1999-12-07,1999-12-08,1999-12-09,1999-12-10,1999-12-13,1999-12-14,...,2022-01-10,2022-01-11,2022-01-12,2022-01-13,2022-01-14,2022-01-17,2022-01-18,2022-01-19,2022-01-20,2022-01-21
Stkcd,,,,,,,,,,,,,,,,,,,,,
1,0.007110,-0.008573,-0.009156,-0.021047,-0.003671,0.000000,-0.013684,0.022412,-0.008351,0.002105,...,-0.000581,0.012798,-0.023550,-0.001176,-0.038280,-0.006736,0.018496,-0.001211,0.050303,0.001154
2,-0.001800,-0.023445,0.018467,0.012693,-0.006267,-0.029730,-0.024141,0.011418,-0.016933,-0.002871,...,0.012334,0.006318,-0.011211,-0.023583,-0.038551,0.008213,0.034499,0.014358,0.009589,-0.021257
3,-0.004847,0.000000,0.008117,0.030596,-0.017188,-0.019078,-0.029173,0.001669,-0.036667,0.024221,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.002445,0.007317,0.037530,0.037340,-0.021372,-0.016092,0.005841,-0.002323,-0.015134,0.049645,...,0.017992,-0.019070,0.010431,0.013139,0.005558,0.036849,0.020435,-0.037875,-0.034389,-0.010309
5,0.002805,-0.027972,-0.007194,-0.002899,-0.005814,0.000000,-0.013158,0.005926,-0.011782,0.010432,...,0.008658,0.004292,0.038462,-0.028807,-0.025424,0.008696,-0.051724,-0.031818,-0.018779,0.009569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.005784,0.000639,0.011494,-0.011364,-0.015326,0.017510,0.001912,-0.021628,-0.032510,-0.022177
605588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.030781,-0.014808,0.009269,-0.007942,-0.022267,0.035824,-0.025198,0.007603,-0.044517,-0.010266
605589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.035078,-0.004328,-0.025210,-0.008323,0.066847,0.100028,-0.038314,-0.054449,0.022472,-0.021978
605598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.065175,-0.035380,-0.014024,0.026805,-0.051145,0.016844,-0.037548,0.020080,-0.077615,-0.031707
605599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.005755,0.066570,-0.021710,-0.005548,-0.031381,-0.000720,-0.047550,0.026475,-0.030951,0.000000

In [25]:
window = 5
factors = []
for i in range(1,window+1):
    factor = data.shift(i)
    factors.append(factor.T)

In [27]:
factors[1]

Trddt,1999-12-01,1999-12-02,1999-12-03,1999-12-06,1999-12-07,1999-12-08,1999-12-09,1999-12-10,1999-12-13,1999-12-14,...,2022-01-10,2022-01-11,2022-01-12,2022-01-13,2022-01-14,2022-01-17,2022-01-18,2022-01-19,2022-01-20,2022-01-21
Stkcd,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,0.007110,-0.008573,-0.009156,-0.021047,-0.003671,0.000000,-0.013684,0.022412,...,-0.001749,0.004673,-0.000581,0.012798,-0.023550,-0.001176,-0.038280,-0.006736,0.018496,-0.001211
2,NaN,NaN,-0.001800,-0.023445,0.018467,0.012693,-0.006267,-0.029730,-0.024141,0.011418,...,-0.005668,0.039905,0.012334,0.006318,-0.011211,-0.023583,-0.038551,0.008213,0.034499,0.014358
3,NaN,NaN,-0.004847,0.000000,0.008117,0.030596,-0.017188,-0.019078,-0.029173,0.001669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0.002445,0.007317,0.037530,0.037340,-0.021372,-0.016092,0.005841,-0.002323,...,-0.003183,-0.036496,0.017992,-0.019070,0.010431,0.013139,0.005558,0.036849,0.020435,-0.037875
5,NaN,NaN,0.002805,-0.027972,-0.007194,-0.002899,-0.005814,0.000000,-0.013158,0.005926,...,0.008696,-0.004310,0.008658,0.004292,0.038462,-0.028807,-0.025424,0.008696,-0.051724,-0.031818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001248,-0.030530,0.005784,0.000639,0.011494,-0.011364,-0.015326,0.017510,0.001912,-0.021628
605588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.014563,-0.010073,0.030781,-0.014808,0.009269,-0.007942,-0.022267,0.035824,-0.025198,0.007603
605589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.002224,-0.003606,-0.035078,-0.004328,-0.025210,-0.008323,0.066847,0.100028,-0.038314,-0.054449
605598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.100059,0.100054,-0.065175,-0.035380,-0.014024,0.026805,-0.051145,0.016844,-0.037548,0.020080
605599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.029178,-0.050546,-0.005755,0.066570,-0.021710,-0.005548,-0.031381,-0.000720,-0.047550,0.026475

In [28]:
date_series = target.columns
date_series

DatetimeIndex(['1999-12-01', '1999-12-02', '1999-12-03', '1999-12-06',
               '1999-12-07', '1999-12-08', '1999-12-09', '1999-12-10',
               '1999-12-13', '1999-12-14',
               ...
               '2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13',
               '2022-01-14', '2022-01-17', '2022-01-18', '2022-01-19',
               '2022-01-20', '2022-01-21'],
              dtype='datetime64[ns]', name='Trddt', length=5367, freq=None)

In [29]:
poly = PolynomialFeatures(3)
date_tables = []
for date in date_series:
    target_column = target.loc[:,date]
    target_column.name = 'y'
    factor_columns = []
    for i in range(len(factors)):
        table = factors[i]
        column = table.loc[:,date]
        factor_columns.append(column)
    factor_table = pd.concat(factor_columns,axis=1)
    factor_table = factor_table.dropna()
    if factor_table.empty:
        continue
    factor_poly_table = pd.DataFrame(poly.fit_transform(factor_table.to_numpy()))
    date_table = pd.concat([target_column,factor_poly_table],axis=1)
    date_tables.append(date_table)

In [30]:
date_tables[0]

,y,0,1,2,3,4,5,6,7,8,...,46,47,48,49,50,51,52,53,54,55
0,NaN,1.0,-0.003671,-0.021047,-0.009156,-0.008573,0.007110,0.000013,0.000077,0.000034,...,-7.675689e-07,-7.186946e-07,5.960479e-07,-6.729324e-07,5.580951e-07,-4.628550e-07,-6.300840e-07,5.225589e-07,-4.333832e-07,3.594254e-07
1,0.000000,1.0,-0.006267,0.012693,0.018467,-0.023445,-0.001800,0.000039,-0.000080,-0.000116,...,6.297803e-06,-7.995450e-06,-6.138542e-07,1.015072e-05,7.793259e-07,5.983308e-08,-1.288697e-05,-9.894024e-07,-7.596180e-08,-5.832000e-09
2,-0.029730,1.0,-0.017188,0.030596,0.008117,0.000000,-0.004847,0.000295,-0.000526,-0.000140,...,5.347941e-07,0.000000e+00,-3.193479e-07,0.000000e+00,-0.000000e+00,1.906960e-07,0.000000e+00,-0.000000e+00,0.000000e+00,-1.138726e-07
3,-0.019078,1.0,-0.021372,0.037340,0.037530,0.007317,0.002445,0.000457,-0.000798,-0.000802,...,5.286104e-05,1.030600e-05,3.443785e-06,2.009299e-06,6.714141e-07,2.243553e-07,3.917411e-07,1.309016e-07,4.374121e-08,1.461627e-08
4,-0.016092,1.0,-0.005814,-0.002899,-0.007194,-0.027972,0.002805,0.000034,0.000017,0.000042,...,-3.723157e-07,-1.447653e-06,1.451689e-07,-5.628821e-06,5.644517e-07,-5.660257e-08,-2.188621e-05,2.194724e-06,-2.200844e-07,2.206981e-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
    date_series = target.columns
    date_tables = []
    for table in factor_tables:  # 取factors, target日期的交集。
        date_series = [date for date in date_series if date in table.columns]
    
    for date in date_series:
        target_column = target.loc[:,date]
        target_column.name = 'y'
        factor_columns = []
        for i in range(len(factor_names)):
            name = factor_names[i]
            table = factor_tables[i]
            column = table.loc[:,date]
            column.name = name
            factor_columns.append(column)
        date_table = pd.concat([target_column]+factor_columns,axis=1)
        date_tables.append(date_table)